In [1]:
import gym
import random
import numpy as np
import time
from IPython.display import clear_output

from stable_baselines.deepq.policies import MlpPolicy
from stable_baselines import A2C
from stable_baselines.common.env_checker import check_env

/home/oc/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/oc/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/oc/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/oc/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: Futu

In [2]:
from routing_001.envs import Routing

In [3]:
env = gym.make('routing-v0')

MultiDiscrete([8 8 8 8 8 8 8 8])
MultiDiscrete([5 5 5 5 5 5 5 5])


In [4]:
env.reset()

array([0, 0, 0, 0, 0, 1, 0, 0])

In [5]:
action_space_size = len(env.actionspace)
state_space_size = len(env.obsspace)

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
num_episodes = 100
max_steps_per_episode = 5

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [7]:
model = A2C("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=25000)
print('TESTTEST')
    #model.save("netw")

    #del model # remove to demonstrate saving and loading

    #model = DQN.load("netw")

obs = env.reset()
#print('Fist Observation = '+obs)
for i in range(20):
    action, _states = model.predict(obs, deterministic=True)
    obs, rewards, dones, info = env.step(action)
    print('Observation = ')
    print(obs)
    print('Reward = '+str(rewards))
    #env.render()
print('finished')

Wrapping the env in a DummyVecEnv.




Instructions for updating:
Use keras.layers.flatten instead.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

[4 4 7 3 2 7 7 5]
[0 5 4 1 5 3 2 7]
[7 0 2 7 7 2 7 4]
[0 5 3 0 4 2 0 5]
[1 1 3 0 6 4 0 5]
---------------------------------
| explained_variance | -0.148   |
| fps                | 2        |
| nupdates           | 1        |
| policy_entropy     | 16.6     |
| total_timesteps    | 5        |
| value_loss         | 54.5     |
---------------------------------
[6 3 3 4 6 0 4 4]
[0 2 7 1 1 6 1 4]
[2 4 7 6 4 0 5 5]
[5 1 1 3 1 3 1 5]
[3 1 0 4 0 1 4 2]
[4 4 4 2 6 2 6 7]
[0 7 2 5 7 6 0 2]
[7 5 5 3 4 7 4 4]
[4 5 7 5 0 3 0 4]
[3 5 1 2 7 4 6 5]
[4 7 0 1 7 4 7 1]
[7 0 0 3 7 3 2 0]
[5 3 7 1 3 6 6 7]
[3 4 7 2 0 3 4 5]
[6 2 7 4 0 5 0 2]
[6 3 4 7 5 3 7 4]
[2 3 6 7 7 5 4 6]
[6 7 6 5 2 4 7 1

[7 5 4 7 4 2 1 0]
[4 7 6 6 0 7 5 0]
[2 2 2 3 2 5 2 7]
[5 3 7 3 0 5 0 0]
[2 7 6 4 6 7 0 7]
[7 5 6 4 4 7 2 5]
[3 2 5 6 1 3 3 2]
[5 7 2 2 7 7 4 5]
[0 1 0 2 7 3 5 1]
[4 0 5 2 1 4 2 1]
[1 6 1 6 3 3 2 5]
[2 2 4 2 7 7 5 7]
[0 4 7 2 6 0 2 1]
[3 3 5 5 2 1 1 7]
[3 5 3 2 4 4 2 3]
[3 7 0 3 5 2 6 3]
[7 4 7 6 0 3 7 3]
[7 3 3 0 1 6 7 7]
[4 7 7 7 6 1 7 7]
[2 0 6 0 3 5 4 0]
[7 1 7 4 5 1 4 6]
[5 1 6 7 4 4 1 7]
[3 2 0 2 3 2 4 3]
[4 7 0 4 7 6 5 3]
[0 5 1 3 1 2 4 3]
[4 2 4 0 3 6 3 7]
[5 0 6 7 2 6 3 4]
[6 5 4 1 2 7 4 1]
[3 1 7 5 1 6 6 5]
[2 5 4 7 7 0 5 4]
[3 5 3 6 6 4 4 1]
[7 4 7 2 7 2 7 0]
[0 4 2 4 7 1 2 3]
[1 5 0 5 4 7 0 7]
[7 5 0 5 1 5 4 3]
[1 6 4 7 5 1 3 7]
[1 2 1 1 7 2 0 5]
[5 0 0 7 6 0 3 6]
[6 0 2 7 5 6 4 5]
[1 5 4 0 1 0 6 4]
[4 7 4 0 7 6 5 3]
[5 7 0 1 7 2 3 4]
[5 6 3 1 0 7 0 4]
[0 5 5 5 3 4 4 2]
[6 6 1 5 6 1 0 1]
[3 6 5 5 0 6 4 3]
[6 5 7 1 5 6 2 3]
[1 5 0 3 4 6 4 2]
[4 6 1 7 5 4 0 2]
[3 5 5 6 6 5 1 6]
[2 1 2 6 5 0 4 0]
[6 1 4 4 1 6 1 0]
[2 6 4 0 2 0 4 5]
[0 6 0 3 1 1 5 6]
[5 6 0 7 3 1 3 0]
[2 1 0 6 7

[1 6 0 1 7 5 1 1]
[1 1 3 4 0 7 0 0]
[4 2 0 0 1 6 4 3]
[1 3 0 1 7 0 1 6]
[7 6 2 2 7 5 4 5]
[6 1 3 7 4 6 5 0]
[2 4 3 7 5 4 7 0]
[5 1 7 5 1 6 7 7]
[4 4 7 0 5 1 3 3]
[5 1 4 3 4 7 7 5]
[3 7 1 5 0 1 5 0]
[4 6 7 4 3 2 1 7]
[6 3 0 6 5 6 5 3]
[3 6 7 3 2 3 1 2]
[5 1 1 4 6 5 1 6]
[5 5 1 2 4 7 7 1]
[2 0 4 7 5 5 4 1]
[1 6 6 5 4 3 6 0]
[5 1 3 4 0 2 2 6]
[2 1 1 4 2 6 6 6]
[4 2 3 6 0 5 3 3]
[1 7 6 7 2 6 6 0]
[5 0 0 3 2 7 6 2]
[0 0 3 4 6 1 2 7]
[6 7 4 2 1 5 4 4]
[3 2 7 2 4 1 0 2]
[4 5 6 4 7 1 5 5]
[4 7 7 2 6 7 7 2]
[5 5 2 5 5 7 0 2]
[0 1 3 7 0 1 4 4]
[1 6 3 7 0 4 7 0]
[4 0 6 4 0 0 0 4]
[7 5 2 2 3 1 2 0]
[3 7 4 5 0 1 2 5]
[5 0 7 3 6 7 7 6]
[6 2 6 4 0 7 4 0]
[4 3 4 1 6 3 0 0]
[2 7 4 2 1 4 0 1]
[0 6 7 1 6 0 2 3]
[1 7 0 7 0 0 5 5]
[4 4 6 3 1 6 3 1]
[4 1 4 5 3 6 6 6]
[6 7 4 4 2 4 6 3]
[1 0 2 6 1 7 1 7]
[6 7 4 1 2 2 7 1]
[4 3 5 6 2 1 4 3]
[3 7 3 4 1 0 2 5]
[7 2 3 2 1 5 1 7]
[1 0 1 6 3 0 3 1]
[5 3 6 5 7 0 5 4]
[2 3 0 5 4 3 1 7]
[7 1 5 5 7 1 5 1]
[0 2 5 5 0 7 7 7]
[4 0 6 6 7 2 3 5]
[0 3 1 1 3 4 5 7]
[0 2 7 4 3

[7 3 6 3 4 2 5 7]
[5 7 7 3 0 3 6 1]
[5 2 5 1 6 5 6 2]
[6 1 4 4 3 3 2 0]
[2 7 7 7 3 5 0 5]
[4 6 5 7 1 2 3 2]
[2 0 2 1 3 0 6 6]
[4 3 1 5 1 1 4 2]
[3 4 3 5 4 5 5 2]
[0 3 3 4 2 0 6 6]
[7 6 6 4 7 0 2 3]
[0 2 7 7 2 2 7 0]
[1 5 5 2 2 3 7 0]
[5 6 4 7 2 6 0 7]
[0 2 4 4 7 2 5 6]
[6 3 3 1 1 7 4 6]
[3 3 4 7 7 6 2 6]
[1 4 6 6 5 0 2 7]
[5 0 5 0 2 4 1 4]
[1 1 0 2 0 7 6 7]
[7 1 0 1 2 7 7 7]
[2 1 4 1 0 0 7 2]
[0 0 5 0 3 6 7 5]
[7 2 6 1 7 4 7 5]
[5 5 7 0 0 0 1 2]
[7 3 5 3 0 7 3 2]
[2 6 6 0 1 4 6 2]
[0 7 2 3 5 2 7 5]
[0 1 2 4 7 6 7 3]
[3 0 2 5 3 0 2 3]
[7 2 0 5 7 1 0 1]
[3 3 7 3 7 0 7 0]
[5 6 7 7 5 6 7 7]
[1 1 0 4 3 7 2 4]
[1 4 7 1 3 1 7 6]
[4 3 2 0 7 7 0 4]
[7 5 5 6 6 0 5 1]
[7 3 7 2 3 0 2 2]
[4 2 2 5 0 0 0 2]
[7 6 4 5 3 3 6 0]
[4 4 2 6 0 3 0 0]
[2 3 6 5 0 6 4 4]
[5 5 4 5 5 1 0 5]
[7 2 6 5 3 7 6 4]
[5 1 6 2 1 5 0 1]
[4 7 7 7 1 6 0 6]
[5 1 0 6 7 7 1 3]
[2 2 1 0 4 3 5 2]
[6 0 1 1 6 2 6 0]
[4 0 4 5 5 6 7 2]
[5 4 3 0 2 6 4 1]
[5 7 2 2 7 6 1 7]
[0 6 2 3 0 4 5 1]
[5 2 2 7 0 4 2 1]
[2 6 0 5 6 1 7 6]
[3 1 7 0 1

[2 0 1 0 3 7 2 7]
[3 2 3 5 5 1 0 5]
[3 0 3 3 4 0 2 4]
[6 2 1 7 4 7 1 4]
[7 0 4 1 4 5 6 1]
[1 6 2 5 4 3 3 7]
[7 3 4 7 0 0 0 6]
[5 6 1 0 5 7 3 1]
[7 3 0 0 6 2 4 6]
[4 7 4 3 3 1 4 7]
[5 1 1 6 2 3 6 2]
[5 1 4 4 1 0 2 6]
[2 1 7 0 7 3 2 7]
[6 4 2 1 5 3 2 6]
[7 6 3 5 4 4 3 5]
[0 4 6 7 3 0 6 0]
[3 4 1 7 5 1 0 0]
[5 6 4 3 4 1 7 0]
[2 3 0 3 4 3 5 3]
[5 2 5 0 5 0 0 2]
[6 6 5 7 7 3 0 7]
[3 6 0 7 2 4 3 1]
[4 3 4 7 3 6 5 0]
[3 1 1 6 7 2 4 4]
[3 3 7 4 4 6 1 1]
[6 6 5 5 6 3 7 2]
[7 7 2 5 6 1 3 3]
[4 5 7 2 3 0 5 2]
[2 5 5 2 3 1 2 4]
[1 1 0 1 6 5 0 7]
[6 7 6 4 7 1 4 3]
[0 3 1 4 6 7 4 6]
[5 4 0 2 2 7 4 7]
[4 5 6 0 6 0 3 1]
[7 2 0 0 0 0 6 3]
[2 7 4 2 3 4 2 2]
[7 1 1 2 5 1 2 3]
[5 1 6 0 3 2 0 0]
[0 5 5 1 0 0 1 4]
[3 0 4 4 2 0 4 4]
[3 4 2 7 5 7 0 3]
[0 3 6 7 2 4 2 7]
[7 5 5 5 0 6 2 7]
[7 2 1 0 2 7 5 4]
[6 6 4 5 1 1 2 2]
[7 1 6 1 7 3 0 6]
[7 3 4 0 1 3 7 6]
[0 6 1 5 3 5 1 0]
[7 5 4 0 4 6 3 0]
[3 6 3 0 0 6 1 0]
[1 1 7 1 1 1 5 3]
[1 2 6 0 0 4 1 2]
[7 2 5 5 3 3 5 1]
[7 5 2 7 0 0 7 7]
[7 5 0 2 0 0 3 5]
[3 1 6 7 2

[1 5 3 6 3 1 5 6]
[7 2 1 4 5 1 1 5]
[3 6 6 7 0 4 7 5]
[0 0 0 4 6 1 1 2]
[6 5 6 3 0 7 6 1]
[4 0 0 5 3 1 5 5]
[0 4 0 6 2 1 5 6]
[0 7 1 6 5 1 6 0]
[7 1 5 3 6 1 6 0]
[2 3 2 7 7 1 5 7]
[1 2 7 6 6 6 1 2]
[0 1 3 4 2 1 4 7]
[1 6 4 5 5 4 7 7]
[2 6 3 5 1 5 1 2]
[7 2 5 1 0 0 2 0]
[3 1 7 4 6 1 2 1]
[0 2 3 0 1 7 3 6]
[1 1 4 0 4 3 0 3]
[0 1 0 7 5 6 0 7]
[1 0 4 5 7 0 5 1]
[1 0 5 5 0 2 7 0]
[3 4 7 6 6 0 6 2]
[1 2 2 0 3 1 7 4]
[6 0 5 2 4 3 6 0]
[1 0 5 0 4 6 5 0]
[0 2 7 6 2 2 7 0]
[1 2 3 0 1 7 5 3]
[1 1 0 0 6 7 3 6]
[1 0 3 7 5 5 0 1]
[2 2 1 4 4 6 1 4]
[1 5 1 4 5 2 1 1]
[3 6 1 3 7 3 4 0]
[0 2 4 0 4 3 3 3]
[7 3 2 5 5 5 1 6]
[2 4 7 1 7 3 2 2]
[4 1 3 1 3 5 2 4]
[7 1 5 1 3 0 2 6]
[4 3 5 3 1 1 1 6]
[1 7 3 6 3 0 3 3]
[5 5 4 4 4 3 0 0]
[2 2 0 4 0 0 3 2]
[3 7 0 4 4 3 5 1]
[5 7 4 3 3 2 2 6]
[5 7 6 1 0 1 4 2]
[0 1 5 0 1 6 0 7]
[7 1 1 2 3 4 2 4]
[3 1 5 1 2 1 3 6]
[0 4 7 3 6 6 6 4]
[5 5 5 7 0 5 1 4]
[1 6 5 1 1 6 3 4]
[1 2 2 6 2 4 2 6]
[2 3 6 4 3 3 1 1]
[2 2 5 4 1 7 2 6]
[1 6 3 2 6 4 2 3]
[0 0 4 1 5 2 5 3]
[2 7 0 6 1

[3 3 5 0 1 4 1 0]
[0 7 1 2 2 1 0 3]
[7 3 6 5 0 1 0 4]
[0 4 6 1 2 3 4 3]
[3 4 5 7 0 2 3 6]
[5 6 7 7 0 1 5 4]
[3 7 3 5 1 4 0 6]
[1 7 2 1 7 4 1 6]
[1 6 0 2 5 4 6 2]
[4 1 4 6 5 1 6 2]
[4 6 2 6 1 3 1 6]
[4 6 3 4 0 4 2 5]
[2 5 3 3 2 0 0 6]
[3 7 6 2 0 7 3 4]
[2 0 1 3 2 6 1 0]
[1 1 4 2 5 1 4 2]
[4 2 6 4 5 7 0 0]
[7 1 0 1 0 6 6 7]
[0 7 7 1 5 7 4 5]
[0 4 1 2 6 1 6 1]
[0 4 3 3 0 3 6 4]
[2 0 2 3 2 4 7 0]
[1 7 4 1 2 0 2 7]
[0 0 4 7 3 6 0 5]
[6 4 5 4 7 6 6 1]
[6 3 2 5 1 1 7 4]
[1 5 5 4 2 4 4 2]
[5 0 7 2 0 5 3 1]
[5 3 0 7 2 1 4 7]
[3 5 1 6 3 6 7 1]
[3 7 0 4 2 3 0 6]
[1 1 3 0 1 1 4 0]
[3 2 7 6 6 3 1 7]
[7 1 1 1 6 5 4 1]
[1 2 6 3 0 2 1 0]
[7 4 7 5 0 3 5 3]
[1 6 3 7 6 7 6 3]
[1 3 3 0 3 0 2 5]
[4 6 3 1 3 1 5 1]
[0 1 0 6 0 1 0 0]
[6 4 7 3 6 3 4 5]
[7 3 1 6 4 5 6 7]
[3 3 4 2 4 1 1 4]
[6 1 0 6 6 7 2 4]
[2 2 7 2 4 1 3 4]
[5 5 0 2 6 7 2 7]
[1 2 5 0 1 6 3 4]
[0 1 0 2 0 6 4 6]
[6 2 7 5 4 0 4 3]
[0 4 1 7 1 0 7 0]
[0 7 2 1 3 1 7 4]
[6 1 1 1 7 0 3 3]
[7 1 1 3 3 0 7 4]
[3 6 7 4 1 7 7 2]
[7 4 6 5 3 7 5 4]
[6 6 5 5 7

[5 0 6 0 7 4 3 7]
[2 4 0 6 5 5 2 5]
[6 4 7 4 5 7 4 6]
[7 4 7 1 5 3 4 1]
[6 2 4 4 4 0 6 7]
[0 3 5 0 7 1 4 6]
[4 6 2 4 7 7 4 1]
[4 2 4 4 2 1 0 3]
[1 0 7 6 5 4 3 2]
[1 1 0 0 7 7 6 4]
[2 7 7 2 6 2 1 3]
[3 7 6 0 2 5 0 2]
[7 4 3 2 7 4 4 1]
[6 1 2 0 5 2 3 6]
[4 3 0 7 0 4 5 3]
[0 6 2 2 5 1 4 3]
[5 3 0 7 7 1 2 0]
[3 5 1 1 3 1 4 7]
[4 7 5 3 1 7 0 1]
[5 6 0 2 4 6 1 5]
[7 4 0 0 2 2 2 6]
[5 3 5 1 0 0 0 2]
[4 3 2 5 1 3 5 6]
[5 4 0 5 2 3 3 1]
[4 6 5 4 3 1 5 7]
[0 6 4 3 7 4 4 5]
[4 0 7 3 4 5 2 6]
[0 7 7 4 0 5 5 1]
[2 3 0 4 5 6 0 3]
[7 7 6 1 1 6 7 0]
[3 2 3 3 4 1 7 6]
[0 5 1 2 3 7 3 2]
[3 3 3 0 5 5 1 6]
[6 2 4 7 2 2 6 6]
[6 5 2 6 0 5 1 5]
[4 1 1 0 6 3 5 0]
[6 4 5 1 5 1 3 3]
[1 0 0 6 4 2 0 1]
[3 7 1 3 6 0 4 5]
[5 1 4 7 5 6 5 3]
[0 3 5 1 6 5 1 1]
[6 0 6 2 2 4 4 1]
[2 2 1 7 1 0 6 4]
[1 0 7 1 1 5 3 3]
[1 5 0 4 5 3 7 3]
[2 7 5 0 1 6 5 6]
[2 6 3 7 6 5 4 0]
[7 2 3 3 0 1 4 7]
[2 6 1 0 7 7 2 1]
[4 5 1 6 1 5 4 4]
[5 0 7 7 3 1 2 0]
[5 1 6 3 5 1 6 6]
[0 7 5 7 2 6 0 7]
[1 2 6 1 2 6 7 6]
[2 2 0 5 7 5 0 2]
[4 7 6 7 3

---------------------------------
| explained_variance | 0.0279   |
| fps                | 302      |
| nupdates           | 700      |
| policy_entropy     | 16.6     |
| total_timesteps    | 3500     |
| value_loss         | 50.1     |
---------------------------------
[4 5 7 3 0 2 3 3]
[6 0 6 7 0 6 3 2]
[4 6 6 7 7 5 3 7]
[5 5 1 1 6 5 7 1]
[6 3 3 2 7 5 1 6]
[3 7 2 4 7 1 2 6]
[4 3 7 1 5 7 5 1]
[7 6 4 4 1 4 4 5]
[1 0 5 3 3 7 1 4]
[1 4 5 5 0 4 1 0]
[3 1 6 7 3 1 4 2]
[1 7 2 4 2 5 3 6]
[5 6 0 4 2 6 7 7]
[0 1 7 0 7 0 6 3]
[0 7 7 5 4 5 2 5]
[5 5 6 5 2 2 5 6]
[3 7 5 6 4 1 1 0]
[7 2 6 3 0 3 7 5]
[6 4 2 6 6 3 0 6]
[3 4 3 7 5 5 7 4]
[4 3 3 2 2 3 1 0]
[1 3 0 6 4 2 7 5]
[1 2 6 3 2 3 2 5]
[0 0 6 7 0 5 7 6]
[3 5 6 1 2 1 1 2]
[6 0 6 7 3 2 5 7]
[3 4 3 1 5 6 5 1]
[7 1 4 4 6 2 4 1]
[1 1 4 2 1 1 1 5]
[5 4 6 1 0 0 5 4]
[4 4 1 6 5 2 4 1]
[3 2 0 6 5 2 2 1]
[6 7 7 0 4 4 6 1]
[2 7 1 3 6 1 4 0]
[3 0 4 5 7 0 5 1]
[3 0 2 1 0 5 6 1]
[5 1 2 6 4 6 1 2]
[6 7 4 4 1 1 3 3]
[2 7 7 2 0 4 0 5]
[1 0 2 7 7 1 7 7]
[3 7 7 1

[4 2 4 0 0 0 5 3]
[1 5 0 6 5 5 7 3]
[0 5 2 6 1 3 2 6]
[5 0 0 7 6 6 7 0]
[3 4 6 1 2 5 1 0]
[7 6 0 0 5 7 7 4]
[1 4 7 1 7 3 5 1]
[2 3 3 2 0 2 6 0]
[2 3 1 5 7 2 6 2]
[7 0 4 0 0 1 4 2]
[6 7 4 0 7 4 4 5]
[6 7 0 0 5 4 1 6]
[4 3 1 6 0 5 1 3]
[0 0 2 6 1 2 0 3]
[6 7 7 6 4 7 2 4]
[2 2 7 7 6 6 7 0]
[7 2 3 7 4 2 3 5]
[5 2 6 7 5 1 1 5]
[0 6 6 0 3 3 0 0]
[0 3 3 0 0 1 6 3]
[5 2 6 4 2 0 0 7]
[0 5 6 6 1 4 3 1]
[3 7 5 4 0 2 4 7]
[5 2 2 1 6 0 7 0]
[5 5 7 5 3 2 3 2]
---------------------------------
| explained_variance | 0.0232   |
| fps                | 294      |
| nupdates           | 800      |
| policy_entropy     | 16.6     |
| total_timesteps    | 4000     |
| value_loss         | 900      |
---------------------------------
[7 2 7 3 6 3 0 3]
[7 6 3 4 4 1 2 5]
[0 2 1 3 6 3 2 5]
[3 1 0 2 7 2 1 6]
[2 7 0 6 4 7 6 2]
[6 1 5 0 3 7 5 4]
[5 7 4 2 5 6 1 7]
[3 3 0 6 5 3 7 7]
[0 7 0 3 6 4 3 7]
[4 1 2 4 3 7 0 1]
[7 5 6 3 6 1 4 5]
[3 5 5 7 6 7 2 0]
[2 3 5 7 0 3 4 7]
[0 0 2 6 5 1 5 3]
[2 7 6 4 7 7 7 0]
[0 5 6 7

[0 5 6 3 2 1 6 1]
[1 5 7 4 3 6 0 6]
[0 7 5 6 7 1 1 3]
[2 2 3 2 7 1 2 1]
[7 2 7 7 7 1 7 7]
[3 1 6 7 0 1 7 4]
[5 5 1 3 1 2 4 1]
[4 4 0 2 6 2 4 1]
[2 0 6 2 1 1 3 1]
[3 6 4 7 7 1 2 0]
[4 1 5 0 2 6 0 5]
[7 4 2 6 4 1 6 2]
[0 5 2 7 0 7 0 4]
[5 7 6 0 7 4 1 1]
[6 7 1 4 4 1 3 0]
[7 4 7 5 4 6 2 6]
[7 3 3 7 0 3 2 2]
[3 2 1 3 5 1 3 0]
[3 6 3 5 3 6 2 5]
[3 6 1 3 0 1 6 7]
[5 6 7 0 0 5 4 0]
[5 5 2 1 0 1 4 3]
[6 2 4 1 4 7 7 2]
[2 4 7 1 2 0 2 4]
[2 2 7 6 1 0 5 6]
[3 4 7 3 0 3 6 1]
[3 1 4 4 1 4 3 4]
[4 1 1 4 1 1 6 4]
[6 2 1 7 0 1 5 3]
[6 4 1 2 1 2 1 6]
[5 7 4 3 7 1 0 7]
[5 1 6 7 1 1 2 3]
[1 2 5 1 2 1 1 6]
[1 3 3 3 7 2 6 6]
[7 4 4 1 6 1 1 5]
[0 3 6 6 7 1 5 6]
[7 1 5 6 0 2 4 2]
[6 2 0 1 7 7 0 2]
[6 1 4 0 7 7 3 4]
[0 1 4 7 5 1 4 1]
[2 1 7 1 7 4 2 6]
[5 7 3 7 2 1 4 1]
[3 1 7 0 7 1 2 2]
[4 2 3 4 5 3 6 0]
[5 3 2 7 1 2 0 6]
[6 0 4 5 3 0 0 6]
[7 4 3 7 2 4 2 6]
[3 5 7 4 6 2 4 0]
[1 7 3 4 6 1 2 7]
[2 7 6 2 7 1 2 1]
[6 5 6 7 0 3 2 6]
[5 7 3 2 1 1 2 2]
[0 2 4 7 7 1 0 2]
[1 3 6 2 5 0 5 7]
[2 3 1 7 3 1 2 3]
[6 3 4 4 4

[3 7 5 3 1 1 4 3]
[2 3 4 1 3 0 0 1]
[7 7 7 2 7 1 2 4]
[7 4 7 4 3 1 0 0]
[6 3 6 4 5 3 1 4]
[2 7 3 7 7 1 4 6]
[3 0 6 7 3 1 7 3]
[3 5 7 5 5 1 6 7]
[2 3 5 6 5 1 1 5]
[3 0 6 6 3 3 3 3]
[0 7 4 0 0 1 6 7]
[5 4 1 6 4 6 7 5]
[6 6 7 0 6 1 3 7]
[3 5 4 3 3 1 0 6]
[4 0 1 3 1 6 4 2]
[1 7 5 1 5 1 2 3]
[2 7 2 7 7 1 0 6]
[5 0 3 3 4 1 7 2]
[5 3 0 3 5 1 1 0]
[6 7 1 2 2 1 7 4]
[5 0 2 5 3 1 2 7]
[2 7 2 1 5 1 3 3]
[0 6 0 7 4 5 6 3]
[0 6 1 7 0 1 2 6]
[2 5 5 7 3 1 2 2]
[5 4 5 0 4 6 2 6]
[0 4 3 4 4 1 2 5]
[5 7 3 0 5 1 7 3]
[7 7 2 4 4 1 6 7]
[3 0 3 1 2 0 5 1]
[1 6 2 4 5 6 2 5]
[7 0 0 4 2 7 7 5]
[7 3 1 7 7 1 1 0]
[2 3 4 4 4 1 3 7]
[1 1 3 5 7 7 2 0]
[4 2 5 6 6 1 7 1]
[7 6 6 0 0 1 2 0]
[0 6 2 6 4 1 6 4]
[7 6 4 7 6 1 6 5]
[5 5 5 2 2 1 7 0]
[4 5 3 6 1 1 1 1]
[7 3 2 7 2 1 7 0]
[3 4 5 4 3 1 1 3]
[1 5 6 6 7 1 5 2]
[3 1 6 1 0 1 4 4]
[1 0 1 6 2 1 0 2]
[7 0 2 6 4 1 6 1]
[5 6 3 7 5 1 1 1]
[0 4 4 2 5 1 0 7]
[4 0 2 0 3 1 6 3]
[2 3 0 5 7 7 4 0]
[0 0 0 1 0 1 5 7]
[4 2 4 2 3 1 6 0]
[7 7 3 4 7 1 4 2]
[1 3 2 0 3 1 5 7]
[3 3 7 1 1

[1 0 1 4 3 1 3 0]
[1 3 5 2 2 1 4 5]
[3 2 3 7 2 1 0 1]
[3 0 0 1 6 1 0 3]
[1 4 6 4 5 1 6 6]
[1 1 5 6 5 1 5 3]
[1 3 6 4 2 1 5 3]
[5 3 6 2 7 1 0 6]
[2 1 6 4 1 1 3 5]
[7 1 4 3 6 1 5 2]
[7 7 6 1 4 1 0 4]
[3 1 1 3 5 1 4 1]
[0 2 1 1 2 4 1 4]
[2 2 3 2 6 1 7 7]
[6 7 2 0 5 1 1 5]
[0 4 6 6 4 1 1 0]
[2 5 1 6 7 1 4 6]
[2 4 1 1 7 1 5 7]
[0 1 4 7 5 1 3 0]
[7 5 3 6 7 3 5 6]
[7 2 4 0 1 1 4 1]
[7 3 5 2 3 1 0 0]
[3 2 5 1 4 1 1 1]
[3 7 2 4 0 1 2 7]
[1 7 0 4 6 6 6 3]
[7 3 2 1 5 3 5 0]
[6 4 1 0 5 1 6 0]
[7 6 6 1 1 1 0 1]
[0 7 6 2 5 1 2 4]
[3 3 0 4 7 1 2 1]
[4 4 0 0 2 1 1 4]
[6 7 4 1 4 5 7 0]
[6 7 5 1 7 4 7 1]
[6 7 3 3 2 1 6 2]
[7 5 4 6 5 1 7 1]
[6 4 4 1 2 1 5 0]
[0 2 3 2 7 1 4 1]
[5 6 4 7 3 1 0 2]
[1 6 1 1 0 1 5 1]
[0 2 5 0 1 1 7 1]
[6 2 0 5 3 1 1 1]
[1 0 2 0 7 1 7 6]
[2 7 7 0 3 1 1 1]
[6 3 6 3 3 1 0 3]
[6 0 2 4 4 1 0 5]
[1 1 7 4 1 1 6 1]
[5 7 6 0 3 1 3 5]
[6 0 4 0 4 1 6 6]
[0 1 3 7 4 1 2 1]
[5 6 5 1 4 0 1 5]
[2 6 7 3 1 1 2 2]
[0 1 2 0 4 1 0 7]
[7 7 1 2 2 1 5 0]
[2 6 1 0 6 1 5 5]
[6 0 5 1 0 1 6 1]
[6 2 1 7 1

[1 7 7 3 1 1 1 4]
[1 1 1 7 4 1 0 7]
[7 7 4 1 2 1 1 2]
[3 7 3 1 4 1 1 5]
[4 3 7 1 0 1 7 6]
[6 1 5 2 6 1 7 2]
[6 7 3 7 0 5 1 1]
[2 7 2 1 5 1 4 3]
[5 6 5 0 1 4 4 3]
[2 3 6 3 3 1 4 2]
[5 4 3 4 7 1 3 5]
[7 4 7 2 4 1 0 2]
[7 5 4 5 5 1 1 4]
[4 4 6 2 1 1 0 7]
[1 7 5 1 4 1 3 4]
[7 0 6 0 5 1 4 2]
[2 6 1 1 5 1 1 1]
[5 3 0 2 5 1 1 0]
[1 4 2 7 5 1 1 4]
[1 7 7 4 4 1 3 5]
[5 1 3 2 4 1 5 0]
[3 0 2 2 2 1 6 6]
[4 1 7 4 2 1 0 4]
[6 3 5 2 5 7 6 1]
[6 6 1 7 5 1 1 4]
[2 7 1 4 3 1 7 6]
[1 5 6 0 3 1 5 7]
[5 1 5 2 2 1 0 7]
[1 7 5 6 5 1 7 5]
[6 4 5 0 6 1 0 6]
[7 4 0 4 4 1 1 6]
[1 2 5 2 2 1 3 2]
[7 7 4 2 1 1 5 3]
[7 6 0 1 5 1 0 2]
[3 6 7 4 1 1 2 2]
[3 5 1 6 7 1 7 5]
[1 6 0 0 1 1 7 6]
[6 7 6 6 2 1 7 1]
[6 7 2 7 3 1 3 1]
[7 3 1 5 4 1 0 4]
[5 3 6 0 4 1 5 6]
[3 5 1 7 1 1 1 5]
[7 3 6 1 3 1 7 0]
[6 5 3 0 7 1 7 2]
[6 7 0 6 2 1 6 1]
[3 5 5 1 1 1 0 7]
[0 4 1 4 3 7 0 0]
[7 3 5 2 4 4 6 1]
[4 5 5 1 4 1 5 7]
[7 4 0 6 2 1 0 1]
[4 4 0 1 6 1 7 1]
[3 1 3 6 4 1 2 4]
[7 2 0 7 7 1 7 3]
[7 3 1 7 4 1 0 5]
[4 6 5 5 1 1 2 2]
[4 7 0 6 1

[6 0 0 1 5 1 0 4]
[6 6 5 2 1 1 3 3]
[3 0 5 2 5 1 3 3]
[7 0 5 2 4 1 0 4]
[7 2 4 3 3 1 4 2]
[7 5 6 5 4 1 2 1]
[3 4 0 7 1 1 6 2]
[6 0 7 1 4 1 5 2]
[0 7 2 3 4 1 5 0]
[6 1 1 2 6 1 1 2]
[4 1 5 1 4 1 0 7]
[1 2 3 4 4 1 2 5]
[6 6 3 1 2 1 6 0]
[6 0 4 6 4 1 6 3]
[7 4 4 0 4 0 3 7]
[1 7 4 7 3 1 0 1]
[2 1 1 4 4 1 4 3]
[7 1 3 1 2 1 7 0]
[6 1 4 2 4 1 3 3]
[6 4 3 5 4 1 7 4]
[6 2 3 4 6 1 3 5]
[0 0 4 1 4 1 0 3]
[1 2 6 4 0 1 3 7]
[3 0 5 4 6 1 7 6]
[2 0 5 2 4 1 5 4]
[5 0 5 4 4 1 1 7]
[7 0 1 5 4 1 4 2]
[0 3 3 0 1 1 1 5]
[1 0 3 2 5 1 3 7]
[6 5 4 7 5 1 0 4]
[6 7 1 1 1 1 6 2]
[7 0 3 0 0 1 0 2]
[1 6 2 1 6 1 0 1]
[2 6 4 2 6 0 0 1]
[6 3 2 0 1 1 1 3]
[6 3 7 4 0 1 1 2]
[2 0 5 0 4 1 2 1]
[5 3 0 7 3 3 4 1]
[3 5 1 0 4 1 1 5]
[3 3 4 4 4 1 7 0]
[7 5 6 1 4 1 3 3]
[4 0 4 1 4 1 5 6]
[7 5 0 1 4 1 1 0]
[1 1 1 5 3 1 3 1]
[3 7 3 4 7 1 0 6]
[3 1 1 5 4 1 0 1]
[6 0 7 5 3 1 7 2]
[5 4 6 4 4 1 6 2]
[3 3 1 4 4 1 3 7]
[3 3 5 1 3 1 0 3]
[0 7 7 6 7 1 0 6]
[1 1 7 1 4 1 4 2]
[0 6 4 2 4 1 7 1]
[6 6 4 6 2 1 4 7]
[1 5 7 4 4 6 1 7]
[0 0 4 4 0

[5 4 4 7 4 1 0 3]
[7 6 3 2 0 1 2 5]
[7 6 0 4 5 1 5 2]
[4 5 2 7 7 7 0 0]
[6 3 6 1 1 1 5 7]
[2 0 7 7 4 1 7 1]
[2 2 6 5 2 1 2 3]
[1 2 4 3 0 1 3 4]
[2 4 2 5 3 1 0 0]
[5 5 1 1 1 6 1 4]
[5 1 5 3 0 1 1 3]
[0 0 3 6 2 1 1 2]
[6 2 0 1 3 1 5 2]
[2 5 5 3 4 1 0 4]
[3 6 5 6 6 1 7 7]
[6 0 3 3 4 1 7 3]
[7 0 3 2 7 1 7 3]
[6 6 4 4 3 4 1 3]
[5 0 3 7 4 1 6 5]
[1 5 5 4 6 1 5 4]
[1 0 2 0 3 1 4 7]
[0 4 1 6 0 1 4 3]
[1 5 3 2 0 1 0 4]
[6 5 1 3 5 1 5 4]
[7 3 4 4 4 1 1 5]
[6 6 3 2 3 1 0 5]
[1 0 2 5 3 1 6 7]
[6 1 2 5 5 1 7 2]
[1 0 4 6 4 1 0 3]
[1 3 3 7 4 1 4 3]
[7 0 5 6 0 1 5 3]
[6 5 7 4 7 1 2 7]
[6 5 4 5 4 1 1 1]
[7 0 3 3 4 1 6 3]
[3 5 6 3 4 1 7 2]
[6 5 1 5 0 1 7 2]
[7 5 0 4 5 1 1 4]
[6 0 3 0 1 1 5 5]
[1 7 1 1 5 1 0 2]
[6 4 7 5 7 1 1 3]
[5 5 7 4 4 2 1 0]
[0 5 6 7 4 1 7 5]
[0 5 7 3 4 1 2 1]
[6 5 0 6 0 1 0 1]
[0 6 1 1 7 1 7 1]
[5 2 2 3 6 1 1 5]
[3 5 7 2 2 1 7 4]
[7 1 3 0 0 1 7 5]
[6 5 1 2 4 1 7 7]
[5 1 0 3 1 1 7 2]
[7 3 2 6 1 1 5 7]
[6 0 7 6 3 1 4 3]
[1 1 3 6 2 5 1 3]
[5 5 6 5 0 1 2 6]
[0 6 5 4 1 1 7 0]
[2 3 3 2 4

[1 2 1 4 5 1 2 3]
[5 7 3 7 3 1 1 3]
[4 4 3 5 1 1 1 0]
[4 5 3 5 7 1 0 1]
[1 1 1 5 4 1 0 3]
[6 0 1 4 5 1 3 1]
[5 5 5 5 2 1 1 4]
[6 1 5 0 0 1 1 3]
[5 6 3 5 3 1 6 3]
[5 7 3 5 1 1 1 3]
[5 2 6 5 3 1 0 3]
[3 4 7 1 7 1 0 5]
[3 2 5 0 3 1 7 2]
[0 1 7 4 4 1 1 1]
[6 5 1 1 4 1 5 3]
[4 3 4 4 4 1 5 1]
[1 0 6 7 1 1 1 6]
[6 2 3 2 1 1 3 5]
[2 6 5 4 5 1 4 3]
[0 6 7 4 5 1 7 7]
[3 0 6 0 1 1 0 3]
[5 5 3 3 6 1 1 7]
[7 7 1 2 4 1 0 4]
[1 5 2 5 5 1 5 7]
[1 1 0 2 2 1 0 1]
[0 0 4 7 3 1 7 0]
[6 0 6 6 1 2 3 3]
[6 4 3 7 4 5 1 5]
[1 5 0 6 5 1 6 3]
[4 7 3 2 6 1 5 4]
[5 5 1 6 0 1 2 1]
[6 6 5 0 6 1 0 4]
[4 6 3 7 5 1 5 4]
[3 5 1 5 3 1 3 0]
[1 2 2 4 5 1 1 5]
[6 4 4 5 1 1 0 1]
[7 0 7 4 4 1 6 7]
[7 5 7 3 5 1 1 3]
[7 4 2 7 0 1 1 7]
[6 0 5 4 4 1 7 3]
[0 3 0 4 4 5 5 7]
[6 3 6 2 1 1 1 6]
[5 4 6 2 6 1 2 5]
[5 0 1 2 3 1 7 2]
[6 6 3 2 2 4 7 4]
[3 4 6 1 5 1 7 4]
[5 7 3 3 4 1 6 1]
[5 6 3 2 4 1 3 7]
[4 5 5 4 1 1 0 7]
[5 3 3 2 5 1 6 1]
[2 0 7 5 3 1 0 7]
[7 0 3 0 4 1 5 2]
[0 3 4 4 3 1 2 3]
[4 5 4 2 5 1 6 1]
[2 6 3 1 3 1 1 3]
[6 1 5 6 6

[2 2 5 4 3 1 3 7]
[6 4 2 6 4 1 3 3]
[4 6 1 5 0 1 0 6]
[1 0 0 5 3 1 2 3]
[4 5 3 2 2 1 0 3]
[6 5 7 4 3 1 1 0]
[0 5 2 1 1 1 0 3]
[2 6 5 5 3 1 1 0]
[2 6 2 6 3 1 0 3]
[1 6 1 0 1 1 1 4]
[6 0 4 2 4 1 0 7]
[3 5 2 7 6 1 0 5]
[1 2 3 4 6 1 0 6]
[5 0 3 4 3 1 5 1]
[6 1 2 4 4 1 0 3]
[6 6 4 4 3 1 1 7]
[3 7 7 6 3 1 1 7]
[6 5 2 1 1 1 2 5]
[2 5 4 2 0 1 5 2]
[6 3 2 6 2 1 6 2]
[7 3 2 6 0 1 0 1]
[4 7 2 0 1 1 4 3]
[3 3 4 6 1 1 0 7]
[6 0 4 0 4 1 1 2]
[3 0 5 1 4 1 0 2]
[1 7 0 5 7 1 0 3]
[6 6 0 4 7 1 4 2]
[6 4 6 4 6 1 0 6]
[2 7 7 3 3 1 0 2]
[6 0 5 7 4 1 4 7]
[0 2 5 4 3 1 0 7]
[6 2 2 3 0 1 7 3]
[5 6 2 5 3 1 3 6]
[1 0 7 6 1 1 1 5]
[3 3 3 1 2 1 7 3]
[6 7 2 6 4 3 5 3]
[6 6 3 6 1 1 0 2]
[1 6 5 6 3 1 6 3]
[6 6 4 6 3 1 2 2]
[1 4 6 6 3 1 5 3]
[1 3 4 6 0 1 3 1]
[1 0 7 5 0 1 7 0]
[1 7 2 5 1 1 4 6]
[5 2 5 5 4 1 6 6]
[6 7 4 6 4 1 0 3]
[3 5 5 2 4 1 0 2]
[1 1 2 5 4 1 1 3]
[6 5 3 7 0 1 0 7]
[1 5 1 6 2 1 0 0]
[6 0 3 0 7 1 7 3]
[4 4 4 5 6 1 6 3]
[2 5 4 7 6 1 4 0]
[6 5 5 4 6 1 2 5]
[6 6 3 5 0 1 2 5]
[1 3 4 3 7 1 6 3]
[6 0 6 2 7

[2 5 7 3 3 1 7 0]
[6 5 4 6 7 1 1 3]
[3 4 5 4 1 1 1 3]
[3 5 2 3 1 1 3 3]
[7 5 5 6 3 1 2 7]
[6 7 0 3 5 1 5 1]
[5 4 7 1 1 1 4 7]
[7 5 6 6 1 1 7 3]
[6 2 2 6 6 1 0 3]
[1 7 4 0 4 1 2 3]
[0 4 1 6 5 1 2 5]
[0 7 4 4 5 1 5 7]
[5 2 4 6 3 1 0 7]
[0 4 5 6 2 1 2 7]
[1 5 3 4 4 1 0 2]
[1 0 0 3 7 1 7 3]
[6 2 6 6 3 1 7 3]
[6 0 1 3 2 1 0 3]
[7 5 5 5 6 1 0 1]
[1 6 4 0 4 1 2 0]
[2 1 3 4 2 1 2 5]
[1 5 2 3 1 1 1 7]
[6 0 6 7 7 1 3 3]
[0 6 7 2 5 1 0 7]
[3 0 1 2 6 0 3 5]
[7 6 1 4 2 1 6 7]
[3 6 4 5 3 1 5 5]
[7 7 6 7 3 1 1 1]
[7 5 6 7 3 1 3 4]
[4 5 3 6 3 1 7 2]
[0 1 6 6 3 1 0 0]
[5 6 5 0 7 1 0 2]
[1 2 2 0 4 1 0 7]
[5 0 3 6 7 1 6 5]
[3 0 4 6 2 1 7 0]
[0 0 4 3 3 1 5 5]
[1 3 3 5 5 1 3 0]
[6 0 4 6 3 1 4 6]
[6 1 4 5 6 1 1 0]
[3 0 3 6 0 1 5 3]
[5 0 6 0 3 1 1 3]
[0 0 5 6 3 1 6 3]
[1 3 4 0 3 2 5 5]
[6 1 3 6 5 1 5 5]
[7 4 7 4 7 1 7 1]
[6 6 4 6 0 1 3 6]
[2 6 5 2 3 1 2 0]
[5 6 2 6 3 1 3 3]
[6 0 3 0 3 1 1 6]
[6 0 3 6 0 1 4 3]
[5 5 3 4 1 1 3 6]
[6 6 1 6 3 1 1 1]
[4 5 4 5 7 1 7 5]
[4 7 3 6 7 5 5 3]
[7 5 6 1 3 1 0 5]
[3 1 5 1 4

[6 5 4 2 6 1 0 0]
[6 0 2 2 3 1 2 3]
[7 0 3 6 6 1 4 5]
[0 5 4 7 3 3 1 7]
[6 6 5 0 7 1 1 1]
----------------------------------
| explained_variance | -4.03e-05 |
| fps                | 267       |
| nupdates           | 1700      |
| policy_entropy     | 14.1      |
| total_timesteps    | 8500      |
| value_loss         | 67.6      |
----------------------------------
[6 0 7 6 6 1 1 2]
[1 0 4 6 7 1 3 6]
[7 6 2 5 3 1 0 7]
[2 0 2 6 0 1 5 2]
[7 5 7 5 3 1 0 7]
[7 4 4 1 4 1 7 3]
[7 7 6 5 5 1 1 6]
[1 5 4 6 3 1 4 5]
[0 6 4 5 0 1 7 3]
[2 6 5 2 1 1 5 3]
[0 6 7 6 4 1 6 0]
[7 0 5 2 1 1 7 0]
[3 6 5 5 1 1 0 0]
[3 5 2 0 4 1 0 1]
[1 4 3 5 3 1 0 7]
[3 5 0 5 3 1 6 6]
[6 0 6 0 6 1 6 4]
[0 1 7 7 4 1 6 7]
[2 1 6 6 3 1 3 3]
[2 6 7 6 3 1 0 6]
[7 6 7 3 1 1 7 7]
[2 5 7 5 1 1 7 7]
[6 0 5 6 1 1 3 7]
[0 0 2 6 3 1 4 5]
[7 6 5 0 4 1 1 5]
[0 0 3 5 6 1 0 5]
[6 2 5 0 5 1 3 7]
[4 5 3 3 6 1 0 1]
[3 5 2 6 3 1 3 3]
[6 5 1 6 4 1 4 7]
[6 6 2 5 0 1 2 2]
[6 6 5 6 6 1 7 7]
[6 6 5 6 4 1 1 3]
[6 4 7 6 6 1 0 7]
[7 0 6 2 5 1 4 3]


[7 3 2 6 1 1 6 6]
[6 6 5 1 5 1 5 3]
[7 6 7 0 3 1 0 3]
[5 5 5 0 1 1 1 3]
[2 2 7 6 4 1 2 5]
[1 5 7 6 1 1 1 6]
[7 6 7 3 1 1 5 5]
[2 0 4 5 2 1 2 7]
[1 6 2 7 5 1 1 0]
[6 3 2 1 3 1 1 5]
[7 0 3 3 7 1 0 6]
[1 6 0 6 6 1 4 3]
[7 6 0 5 2 1 0 2]
[2 1 5 4 4 1 6 3]
[3 6 7 2 0 1 5 3]
[6 4 7 0 4 1 0 2]
[4 0 1 2 1 0 6 6]
[0 5 1 6 5 1 1 3]
[6 0 7 6 6 1 5 4]
[5 7 0 6 2 1 0 1]
[2 5 1 6 7 1 5 3]
[2 2 3 5 3 1 3 7]
[1 0 7 1 1 1 0 3]
[6 6 3 5 1 1 3 3]
[2 3 3 6 2 1 0 3]
[1 0 3 1 1 1 5 7]
[7 2 3 1 6 1 6 0]
[7 7 5 6 5 1 3 7]
[6 5 6 0 7 1 5 5]
[6 3 0 1 3 1 5 3]
[6 5 6 2 4 1 1 6]
[2 7 3 0 4 1 0 3]
[1 3 2 6 0 1 4 7]
---------------------------------
| explained_variance | 0.000552 |
| fps                | 269      |
| nupdates           | 1800     |
| policy_entropy     | 13.9     |
| total_timesteps    | 9000     |
| value_loss         | 70.7     |
---------------------------------
[3 5 2 4 2 1 1 6]
[5 6 2 6 6 1 2 0]
[1 5 4 6 7 1 4 3]
[3 3 3 6 4 1 0 7]
[6 0 6 2 3 1 0 3]
[0 2 6 6 3 1 0 3]
[6 5 2 6 3 1 1 3]
[3 5 7 2

[6 6 6 4 4 1 7 7]
[7 2 3 6 4 1 2 7]
[5 0 5 7 3 1 1 4]
[1 6 4 4 3 1 2 4]
[7 5 4 6 6 1 3 2]
[7 1 7 6 1 1 5 3]
[6 1 0 0 3 1 6 3]
[6 0 7 1 3 1 1 6]
[1 3 7 1 6 1 1 0]
[2 5 7 4 5 1 3 3]
[7 5 7 0 4 1 1 3]
[7 6 4 5 4 1 6 3]
[7 5 4 6 4 1 4 3]
[3 1 3 6 3 1 3 5]
[0 6 1 3 6 1 1 3]
[6 6 0 0 4 1 7 7]
[7 1 1 6 7 1 6 3]
[1 4 4 6 3 1 5 3]
[7 5 7 3 3 1 3 5]
[7 7 5 2 3 1 0 4]
[5 1 7 6 3 1 5 3]
[3 4 5 7 0 1 0 3]
[3 7 5 6 1 1 0 3]
[4 5 7 2 5 1 5 1]
[6 6 3 6 2 1 1 3]
[3 6 4 1 6 1 7 5]
[6 6 3 6 3 1 1 5]
[6 6 3 0 7 1 0 3]
[2 3 6 1 1 1 7 3]
[2 6 3 6 0 1 0 5]
[5 6 3 3 7 1 1 6]
[5 3 3 6 6 1 5 7]
[6 5 7 2 4 1 5 3]
[7 5 2 2 3 1 1 7]
[6 6 7 6 6 1 2 1]
[2 1 0 4 7 1 3 5]
[1 5 5 6 7 1 3 3]
[4 6 3 2 6 1 2 3]
[2 0 7 6 6 1 5 3]
[7 5 5 6 7 1 0 4]
[2 4 2 6 1 1 3 3]
[6 6 3 6 3 1 7 3]
[2 6 5 6 4 1 5 3]
[0 5 2 4 3 1 1 6]
[4 0 7 3 1 1 1 3]
[7 3 3 6 7 1 5 5]
[6 5 5 7 5 1 1 2]
[1 5 7 6 1 1 3 3]
[3 0 5 3 7 5 0 3]
[2 4 6 4 1 1 1 3]
[2 0 2 6 3 1 3 2]
[6 0 2 6 3 1 4 5]
[7 1 6 6 7 1 3 4]
[2 5 0 5 3 1 0 5]
[5 6 6 1 0 1 1 5]
[2 5 3 6 4

[6 1 3 6 2 1 0 3]
[7 0 2 6 4 1 7 3]
[6 2 5 0 0 1 2 3]
[0 0 7 4 1 1 6 2]
[2 7 0 0 2 1 5 3]
[2 5 7 5 6 1 5 7]
[3 6 7 0 2 1 0 7]
[6 7 7 6 2 1 5 3]
[1 5 3 4 4 1 5 0]
[6 2 7 1 4 1 7 3]
[2 3 6 6 6 1 3 3]
[7 5 7 4 3 1 6 7]
[1 5 7 6 3 1 3 2]
[6 6 3 7 4 1 5 3]
[2 5 0 6 6 1 5 3]
[1 7 4 2 4 1 2 6]
[2 0 7 6 4 1 1 1]
[0 5 3 7 6 1 3 4]
[5 6 1 6 4 1 5 3]
[2 4 3 0 4 1 2 0]
[1 6 6 0 6 1 1 0]
[6 2 6 0 1 1 3 3]
[1 0 6 7 3 1 1 1]
[1 6 2 6 6 1 5 1]
[2 7 4 7 0 4 3 2]
[6 2 5 1 4 1 4 7]
[1 6 7 7 3 1 6 3]
[1 6 3 0 7 1 3 3]
[6 0 0 6 3 1 1 3]
[2 6 6 4 4 1 5 3]
[5 6 1 6 3 1 1 3]
[7 0 4 5 4 1 0 3]
[2 7 5 6 3 1 1 4]
[7 6 6 6 3 1 3 4]
[7 1 7 1 3 1 5 7]
[3 5 7 2 1 1 0 0]
[2 7 1 4 7 1 6 7]
[6 6 6 6 7 1 1 2]
[6 5 5 0 2 1 0 7]
[6 0 7 5 7 1 1 3]
[0 2 5 0 5 1 5 3]
[5 3 5 0 7 1 2 5]
[7 0 5 2 4 1 0 4]
[2 0 3 6 7 1 0 3]
[7 1 1 6 6 1 7 3]
[5 6 7 6 3 1 3 7]
[3 6 4 2 6 1 2 3]
[7 0 3 3 6 1 0 3]
[4 0 3 1 4 1 1 3]
[6 3 5 6 6 1 7 4]
[6 1 0 6 1 1 3 3]
[0 4 2 3 0 1 0 3]
[2 0 3 6 7 1 1 3]
[6 5 4 6 2 1 0 0]
[7 0 6 4 2 1 3 7]
[2 3 7 6 1

[4 4 4 0 3 1 3 3]
[0 2 3 6 6 1 1 3]
[6 5 3 0 3 1 1 3]
[2 2 7 6 6 1 0 3]
[0 2 7 6 2 1 4 0]
[7 2 5 6 1 1 7 5]
[2 0 3 6 2 1 6 5]
[5 5 6 2 7 1 4 3]
[7 6 2 2 6 1 5 3]
[6 5 7 6 6 1 0 3]
[3 2 7 0 0 1 6 3]
[6 7 7 3 6 1 3 3]
[7 7 5 6 6 1 7 3]
[6 1 5 6 3 1 3 3]
[6 0 5 4 2 1 1 3]
[4 6 2 6 4 1 5 3]
[2 6 1 2 1 1 1 3]
[6 0 3 4 7 1 3 1]
[6 0 7 6 6 1 4 2]
[2 2 3 3 3 1 0 3]
[0 5 7 6 2 1 2 0]
[2 3 6 5 6 1 0 3]
[2 5 7 6 7 1 1 3]
[2 5 6 6 6 1 1 3]
[2 4 3 6 6 1 5 3]
[3 0 6 6 0 1 7 3]
[6 0 1 2 6 1 3 3]
[6 7 3 2 4 1 2 3]
[5 6 1 3 7 1 3 3]
[7 6 4 6 2 1 1 2]
[3 3 7 6 1 1 0 3]
[5 5 7 4 7 1 4 3]
[3 0 7 5 3 1 2 3]
[1 1 2 6 6 1 3 5]
[4 6 2 2 7 1 3 3]
[4 5 3 0 1 1 5 3]
[1 7 2 1 7 1 0 7]
[4 5 3 4 7 1 6 3]
[0 7 5 6 6 1 1 3]
[1 6 6 3 3 1 3 3]
[4 7 3 6 6 1 0 3]
[3 4 4 5 7 1 2 3]
[6 6 3 3 3 1 6 5]
[7 5 2 5 2 1 4 7]
[7 5 3 2 6 1 6 3]
[6 5 3 6 1 1 7 3]
[3 6 5 7 3 1 0 3]
[3 5 6 6 2 1 1 3]
[7 3 5 3 3 1 0 3]
[2 1 4 6 1 1 1 6]
[1 4 1 0 2 1 4 6]
[2 5 7 7 2 1 1 3]
[2 0 7 6 6 1 3 7]
[1 5 2 0 0 1 1 4]
[1 1 7 4 4 1 3 3]
[6 1 2 6 4

[6 6 7 6 7 1 1 3]
[2 5 5 4 2 1 1 3]
[3 5 3 6 2 1 1 3]
[2 0 3 6 0 1 6 3]
[2 3 2 6 0 1 6 3]
[2 2 0 3 3 1 1 3]
[0 5 7 6 4 1 1 3]
[6 5 3 7 4 1 4 3]
[5 6 7 6 7 1 6 7]
[4 5 2 0 2 1 4 3]
[6 5 3 6 7 1 1 2]
[7 2 5 6 0 1 1 7]
[2 2 3 6 5 1 1 3]
[6 5 7 7 1 1 3 4]
[1 1 1 6 7 1 0 3]
[3 0 1 6 4 1 3 7]
[7 0 1 6 0 1 2 3]
[5 5 4 0 6 1 0 7]
[2 2 4 1 3 1 1 3]
[5 0 3 0 7 1 0 2]
[4 0 6 6 4 1 3 3]
[6 6 1 3 6 1 5 3]
[6 5 7 0 4 1 1 4]
[1 1 3 6 4 1 5 5]
[4 0 5 0 3 1 3 3]
[1 6 5 0 6 1 5 7]
[6 5 5 6 3 1 2 3]
[7 5 7 6 6 1 3 5]
[3 0 3 6 7 1 3 3]
[6 0 3 2 0 1 1 3]
[2 1 3 0 4 1 3 5]
[6 0 1 6 6 1 3 3]
[3 0 3 0 6 1 6 3]
[7 0 1 4 0 1 6 3]
[7 2 7 3 6 1 3 3]
[2 0 6 3 5 1 1 3]
[6 1 7 6 6 1 6 5]
[6 6 0 6 4 1 1 3]
[6 2 7 6 6 1 3 3]
[2 0 5 6 0 1 6 1]
[3 1 5 6 7 1 6 5]
[5 7 2 6 7 1 6 2]
[5 0 1 0 3 1 3 3]
[0 5 4 0 6 1 3 3]
[4 6 7 6 4 1 6 7]
[3 5 3 1 0 1 0 2]
[7 1 6 6 4 1 3 3]
[5 7 5 6 0 1 1 3]
[2 5 7 6 0 1 3 3]
[6 6 3 0 1 1 1 3]
[5 6 6 5 6 1 3 4]
[2 6 7 6 2 1 3 7]
[7 5 4 6 0 1 6 3]
[5 6 7 1 6 1 1 6]
[5 0 1 0 0 1 3 6]
[6 6 6 0 3

[1 4 2 6 4 1 5 3]
[2 0 5 0 3 1 3 3]
[6 0 3 0 4 1 3 3]
[5 6 2 0 2 1 2 3]
[7 3 2 0 1 1 3 3]
[7 4 1 1 6 1 5 3]
[1 5 7 6 0 1 3 7]
[6 5 6 0 4 1 5 3]
[6 0 5 1 3 1 5 3]
[7 6 3 6 4 1 0 3]
[0 4 1 6 4 1 3 3]
[2 0 3 3 1 1 1 3]
[6 5 2 1 4 1 1 3]
[7 0 2 0 4 1 5 3]
[7 0 7 6 4 1 0 3]
[7 6 7 2 5 1 5 7]
[1 6 7 6 4 1 3 3]
[5 1 5 0 3 1 3 3]
[6 2 5 6 2 1 1 4]
[3 7 6 3 6 1 1 5]
[5 0 3 1 6 1 0 3]
[6 0 4 0 4 1 6 3]
[3 5 3 6 2 1 5 3]
[2 6 3 3 6 1 3 3]
[6 6 6 6 4 1 1 4]
[4 0 7 0 4 1 1 3]
[3 5 3 6 3 1 3 3]
[5 7 7 6 4 1 5 3]
[1 3 7 6 2 1 3 3]
[5 0 6 6 0 1 6 3]
[5 0 5 4 2 1 6 3]
[3 0 7 6 4 1 1 7]
[2 1 6 0 1 1 1 3]
[5 0 7 0 6 1 3 3]
[3 0 1 6 1 1 5 3]
[5 0 7 5 4 1 1 3]
[2 5 1 2 4 1 0 3]
[4 3 7 6 4 1 0 4]
[2 0 7 6 3 1 1 7]
[6 4 5 6 1 3 3 2]
[2 4 6 5 4 1 3 2]
[5 1 1 0 4 1 5 3]
[4 5 3 0 0 1 1 5]
[7 0 7 6 7 1 1 7]
[5 0 7 6 7 1 1 3]
[3 6 3 6 4 3 1 3]
[1 0 3 0 4 1 6 3]
[7 1 7 0 0 1 2 3]
[5 5 3 6 0 1 6 3]
[7 2 3 0 4 1 5 5]
[6 1 7 6 4 1 6 3]
[2 5 6 2 0 1 6 3]
[1 5 7 4 4 1 3 2]
[5 0 7 6 3 1 1 3]
[7 0 3 0 7 1 1 3]
[6 1 5 6 4

[3 0 2 6 4 1 3 3]
[6 2 7 6 6 1 3 3]
[7 0 5 6 4 1 1 3]
[4 2 3 1 4 1 1 3]
[2 0 5 0 4 1 1 5]
[5 0 7 0 4 1 5 3]
[2 7 7 0 6 1 0 3]
[1 2 7 6 7 1 6 3]
[2 5 6 6 4 1 3 5]
[2 6 7 0 4 1 3 3]
[6 0 0 7 4 1 2 3]
[7 0 2 4 4 1 1 3]
[6 0 1 6 4 1 6 3]
[3 6 7 0 4 1 1 3]
[2 2 7 2 4 1 3 3]
[4 3 7 6 3 1 3 3]
[5 5 3 6 4 1 1 3]
[6 5 1 0 4 1 5 3]
[1 5 7 6 4 1 3 3]
[1 5 1 6 4 1 0 3]
[0 5 2 0 4 1 5 3]
[1 0 5 2 2 1 4 3]
[2 4 3 1 4 1 1 3]
[7 0 7 6 4 1 3 3]
[0 5 7 6 4 1 6 3]
[5 6 2 2 4 1 7 3]
[6 1 1 6 4 1 2 3]
[7 4 2 0 5 1 3 3]
[3 3 2 6 3 1 0 3]
[6 0 7 0 4 1 3 3]
[6 5 5 0 4 1 1 3]
[5 0 3 4 4 1 3 4]
[2 4 7 6 4 1 6 3]
[7 6 7 0 4 1 3 3]
[1 4 3 1 4 1 1 5]
[5 7 7 0 6 1 4 3]
[6 0 7 0 4 1 3 3]
[3 5 1 6 4 1 0 3]
[7 1 7 6 4 1 1 3]
[6 0 7 6 7 1 1 3]
[1 0 7 1 4 1 1 3]
[2 6 7 6 4 1 5 3]
[5 1 7 6 1 1 0 3]
[7 0 7 0 6 1 1 3]
[5 0 6 6 4 1 6 4]
[7 5 1 0 4 1 1 3]
[6 5 5 6 4 1 3 3]
[1 5 3 0 4 1 0 3]
[2 5 7 7 7 1 1 3]
[2 1 2 6 4 1 0 3]
[0 2 7 6 4 1 3 3]
[6 0 7 6 7 1 1 3]
[6 3 0 0 4 1 1 3]
[5 6 2 0 4 1 1 3]
[4 5 7 6 4 1 6 3]
[3 4 7 0 4

[7 3 7 0 4 1 0 3]
[4 2 7 6 4 1 1 3]
[6 3 7 6 4 1 3 3]
[1 5 3 0 4 1 0 3]
[2 1 4 6 4 1 6 5]
[2 0 7 6 4 1 1 3]
[4 4 5 0 4 1 3 7]
[6 6 3 6 4 1 3 1]
[1 5 6 6 4 1 5 3]
[6 1 3 1 4 1 3 3]
[2 2 7 2 5 1 3 3]
[2 6 2 6 0 1 0 3]
[2 5 2 1 4 1 3 3]
[5 3 5 0 4 1 0 3]
[7 4 3 0 4 1 3 3]
[0 6 5 6 5 1 3 4]
[6 6 3 6 4 1 4 3]
[6 6 7 0 4 1 3 3]
[5 6 7 0 4 1 1 3]
[5 4 3 6 4 1 1 3]
[5 5 7 6 4 1 1 3]
[3 0 6 6 4 1 3 1]
[2 4 7 0 4 1 0 3]
[6 2 6 6 4 1 1 3]
[1 7 7 4 4 1 6 3]
[6 5 7 6 4 1 0 5]
[2 3 5 0 4 1 3 3]
[6 5 5 0 4 1 3 7]
[3 0 7 6 4 1 0 3]
[0 0 7 6 4 1 1 3]
[5 6 6 0 4 1 3 3]
[2 6 3 6 4 1 1 6]
[7 0 5 6 4 1 3 3]
[7 3 7 6 4 1 1 3]
[2 4 7 6 4 1 0 3]
[7 6 5 6 4 1 3 3]
[3 6 2 6 4 1 1 7]
[2 0 2 0 4 1 3 3]
[5 6 3 6 4 1 3 3]
[5 5 7 6 4 1 6 2]
[2 3 7 6 4 1 4 5]
[4 2 2 0 4 1 3 3]
[1 3 5 6 4 1 1 3]
[2 5 7 0 4 1 4 7]
[7 6 7 2 4 1 3 3]
[4 6 3 6 4 1 3 3]
[6 2 3 2 4 1 3 3]
[7 7 2 6 6 1 1 3]
[6 2 7 0 4 1 3 7]
[6 5 2 6 4 1 3 3]
[3 5 3 4 3 1 1 3]
[3 3 0 6 4 1 3 3]
[2 1 7 6 4 1 3 2]
[5 5 7 0 4 1 2 3]
[1 1 7 2 4 1 3 7]
[7 5 6 6 4

[5 4 7 6 4 1 3 1]
[3 0 7 6 6 1 1 3]
[5 4 7 6 4 1 0 3]
[2 0 2 4 0 1 3 3]
[7 5 7 6 3 1 3 2]
[1 5 7 6 4 1 3 4]
[6 5 1 0 4 1 1 3]
[2 2 3 6 0 1 1 3]
[3 5 4 6 4 1 1 4]
[2 1 3 1 4 1 3 3]
[3 5 7 7 4 1 3 3]
[0 0 7 4 4 1 1 3]
[7 3 3 0 4 1 6 4]
[5 5 1 4 2 1 4 3]
[4 4 3 2 4 1 3 6]
[5 0 2 6 4 1 3 5]
[5 0 7 6 4 1 1 3]
[1 0 7 6 6 1 0 3]
[1 6 4 2 4 1 0 3]
[1 2 3 0 2 1 3 3]
[5 4 3 6 4 1 1 3]
[3 6 4 6 4 1 4 3]
[7 6 0 6 5 1 0 3]
[7 6 7 6 4 1 0 3]
[5 5 7 0 4 1 3 3]
[7 3 7 2 4 1 4 3]
[2 2 3 5 4 1 7 5]
[7 0 5 2 4 1 3 2]
[1 6 7 0 4 1 0 3]
[2 4 3 6 1 1 1 3]
[7 5 3 4 4 1 6 3]
[1 5 7 6 3 1 6 3]
[5 2 7 2 4 1 3 3]
[1 5 6 6 4 1 6 3]
[4 2 6 2 4 1 3 5]
[2 7 7 6 4 1 6 3]
[7 0 7 2 4 1 3 3]
[4 1 3 6 4 1 3 3]
[6 5 2 0 4 1 3 3]
[6 6 5 3 4 1 5 3]
[1 0 7 6 7 1 5 3]
[2 6 7 0 4 1 4 3]
[2 6 7 0 4 1 0 3]
[3 4 3 2 4 1 6 3]
[2 2 3 6 4 1 1 3]
[7 2 7 4 4 1 1 3]
[3 1 5 6 4 1 3 3]
[2 0 7 0 4 1 3 3]
[2 0 7 6 4 1 1 3]
[5 1 3 6 4 1 3 3]
[4 0 7 6 4 1 4 3]
[5 0 6 6 7 1 0 5]
[6 5 7 1 4 1 3 3]
[1 5 7 6 4 1 7 6]
[1 6 7 0 4 1 5 3]
[2 0 2 6 7

[1 5 7 0 4 1 0 3]
[2 0 2 0 4 1 1 3]
[5 6 7 0 4 1 3 2]
[5 6 7 0 4 1 5 3]
[7 2 7 6 2 1 3 3]
[5 7 7 0 2 1 5 3]
[2 0 7 0 0 1 3 3]
[6 2 4 6 6 1 7 3]
[4 5 7 6 4 1 1 5]
[2 4 7 1 0 1 3 3]
[2 2 7 0 4 1 6 3]
[1 6 3 2 4 1 1 3]
[2 2 7 0 6 1 3 3]
[2 5 7 2 4 1 1 3]
[5 0 7 6 4 1 3 3]
[6 5 5 6 0 1 3 3]
[5 4 3 6 4 1 3 3]
[7 5 2 6 4 1 1 6]
[2 6 6 0 0 1 1 3]
[6 2 7 6 4 1 6 3]
[5 2 7 0 4 1 3 5]
[5 5 7 6 4 1 3 3]
[0 5 7 2 4 1 5 3]
[5 2 6 6 4 1 3 5]
[3 0 7 3 4 1 3 2]
[5 5 7 6 4 1 6 5]
[1 5 7 6 4 1 3 4]
[1 1 7 6 3 1 1 2]
[0 5 3 0 3 1 1 5]
[4 5 4 2 4 1 3 3]
[7 4 7 7 4 1 0 3]
[0 5 6 0 6 1 3 3]
[5 6 7 6 2 3 3 3]
[5 5 7 0 4 1 3 3]
[7 0 7 5 4 1 5 2]
[5 5 7 0 4 1 3 3]
[1 0 7 7 4 1 5 2]
[5 2 6 0 4 1 3 3]
[4 0 4 6 4 1 3 2]
[6 0 7 6 4 1 6 4]
[7 6 6 6 4 1 1 3]
[2 0 3 7 1 1 3 0]
[1 6 7 6 3 1 3 7]
[3 4 3 2 7 1 3 3]
[2 3 7 6 4 1 6 5]
[2 1 5 3 7 1 5 3]
[7 5 7 0 4 1 3 3]
[7 1 7 6 4 1 3 3]
[7 5 7 6 4 1 5 3]
[3 0 7 0 1 1 3 3]
[2 0 4 0 4 1 6 3]
[5 7 7 0 4 1 3 5]
[1 4 7 6 4 1 6 3]
[2 0 7 0 6 1 3 7]
[7 6 7 6 4 1 0 3]
[1 1 5 6 4

[2 1 6 6 4 1 1 3]
[2 0 5 2 4 1 3 4]
[5 5 7 6 7 1 3 3]
[5 0 7 3 4 1 5 4]
[5 0 7 0 4 1 3 0]
[7 0 4 6 4 0 3 3]
[6 6 7 6 7 1 5 3]
[2 4 1 3 1 1 5 3]
[1 5 6 6 1 1 1 3]
[2 2 7 6 4 1 3 3]
[5 2 7 6 4 1 3 3]
[7 0 7 6 4 1 3 4]
[6 1 3 6 4 1 3 3]
[2 0 5 0 4 1 1 3]
[2 0 7 6 4 1 5 3]
[2 5 6 4 3 1 3 2]
[6 4 7 6 4 1 3 3]
[7 2 7 5 4 1 5 3]
[3 0 6 6 4 1 4 3]
[5 0 3 6 4 1 2 3]
[2 5 5 0 4 1 3 3]
[6 0 7 2 4 1 5 7]
[7 6 6 0 4 1 4 3]
[6 3 7 0 4 1 5 3]
[5 5 3 0 0 1 3 3]
[6 2 7 6 2 1 3 3]
[2 0 7 6 4 1 3 3]
[3 0 5 6 4 1 1 3]
[3 0 7 6 4 1 5 3]
[2 1 7 0 4 1 3 3]
[5 0 7 6 7 1 6 3]
[5 0 7 1 4 1 3 3]
[2 5 3 0 4 1 3 3]
[6 0 2 0 4 1 0 3]
[0 5 7 0 4 1 3 3]
[6 5 3 6 4 1 3 3]
[5 0 7 3 4 1 1 2]
[6 0 5 2 1 1 3 3]
[7 0 7 6 4 1 3 5]
[7 4 0 6 4 1 3 3]
[5 4 1 0 4 5 5 3]
[5 5 1 6 4 1 6 3]
[2 0 7 6 0 1 3 3]
[3 5 7 7 4 1 0 2]
[2 5 6 0 4 1 6 2]
[1 0 7 0 4 1 3 3]
[6 6 7 0 4 1 5 5]
[6 0 3 6 2 1 3 3]
[7 0 5 6 4 1 3 4]
[2 5 7 6 4 1 4 3]
[7 0 7 0 4 1 7 3]
[5 0 7 6 4 1 3 3]
[6 6 7 6 4 1 3 7]
[7 4 7 0 3 1 3 3]
[5 0 6 6 4 1 3 3]
[0 1 6 6 4

[2 2 7 6 6 1 3 3]
[5 0 7 6 4 1 1 2]
[6 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[5 4 7 6 4 1 5 3]
[6 0 3 6 4 1 3 3]
[0 0 5 6 4 1 1 3]
[6 0 7 6 4 1 3 3]
[2 0 3 6 4 1 3 3]
[5 2 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 5 6 6 4 1 3 3]
[1 6 5 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 7 4 1 6 2]
[6 0 7 6 4 1 3 2]
[7 0 7 6 6 1 3 3]
[5 0 2 1 4 1 3 3]
[5 4 2 0 4 1 3 3]
[3 0 7 3 4 1 3 2]
[6 5 7 2 4 1 1 3]
[6 7 7 0 4 1 1 3]
[6 4 2 0 4 1 3 3]
[5 4 6 6 4 1 3 4]
[6 0 7 6 4 1 5 3]
[7 6 7 2 4 1 0 2]
[7 0 7 7 4 1 0 3]
[2 5 7 6 4 1 3 3]
[3 0 7 6 4 1 3 3]
[6 0 7 6 3 1 3 3]
[6 5 7 7 6 1 4 3]
[1 2 6 6 6 1 4 5]
[6 4 7 1 6 1 3 3]
[7 2 6 2 4 1 1 3]
[2 6 7 0 6 1 0 3]
---------------------------------
| explained_variance | 0.000293 |
| fps                | 268      |
| nupdates           | 2800     |
| policy_entropy     | 9.38     |
| total_timesteps    | 14000    |
| value_loss         | 48.8     |
---------------------------------
[6 0 7 6 2 1 3 3]
[6 5 7 4 3 1 3 3]
[2 0 7 6 3 1 3 7]
[7 0 7 6 6 1 3 5]
[2 5 7 6 6 1 3 3]
[1 5 7 2

[7 0 7 6 4 1 3 3]
[2 0 7 6 4 1 1 4]
[7 2 7 0 1 1 3 3]
[7 4 7 6 4 1 3 3]
[7 0 7 7 4 1 3 3]
[3 1 7 6 4 1 6 3]
[7 6 6 6 4 1 6 1]
[7 0 7 0 6 1 7 3]
[6 0 7 6 2 1 1 3]
[7 4 0 6 6 1 3 5]
[6 0 7 0 4 1 4 3]
[2 1 5 2 0 1 5 3]
[2 1 7 4 0 1 5 3]
[5 1 7 2 1 1 3 3]
[4 0 7 0 4 1 3 3]
[7 0 6 6 3 1 5 2]
[6 0 7 6 0 1 3 3]
[5 4 6 6 4 1 1 6]
[6 0 6 6 4 1 1 5]
[2 0 6 6 4 1 6 3]
[7 1 7 6 3 1 3 3]
[0 6 7 6 4 1 3 3]
[7 1 7 1 2 1 3 3]
[5 5 3 6 3 1 3 2]
[7 4 6 6 4 1 3 5]
[7 0 7 1 4 1 1 3]
[2 0 0 4 4 1 3 5]
[2 5 5 6 4 1 3 2]
[6 0 7 6 4 1 4 3]
[4 0 0 6 4 1 0 5]
[7 4 4 6 4 1 3 3]
[7 0 7 0 4 1 3 3]
[2 0 7 4 0 1 5 3]
[7 0 6 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[1 0 7 0 1 1 3 5]
[7 1 7 3 4 1 3 3]
[4 0 2 6 4 1 4 1]
[2 2 7 6 4 1 3 2]
[2 3 3 0 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 4 6 3 1 6 2]
[6 1 7 6 4 1 3 3]
[6 0 5 0 4 1 3 5]
[5 0 7 6 4 1 3 3]
[2 0 7 3 0 1 3 4]
[6 6 7 0 4 1 3 5]
[2 4 7 6 4 1 3 3]
[7 0 7 0 0 1 3 3]
[0 3 2 6 4 1 1 3]
[6 2 1 3 4 1 3 3]
[7 0 2 6 4 1 3 2]
[5 4 7 6 6 1 3 3]
[7 0 7 6 3 1 1 3]
[5 4 7 6 4 1 3 5]
[2 1 7 4 7

[3 0 3 3 6 1 3 7]
[7 1 6 6 0 1 5 3]
[6 0 7 0 4 1 3 4]
[7 5 7 0 4 1 3 3]
[7 5 7 6 2 1 3 3]
[2 5 7 6 5 1 3 3]
[7 2 6 1 4 1 2 3]
[5 0 7 3 0 1 3 3]
[6 2 6 6 4 1 3 3]
[7 6 6 6 4 1 3 3]
[5 1 7 0 4 1 3 7]
[6 0 5 1 0 1 5 4]
[7 3 6 6 4 1 3 3]
[6 5 2 6 4 1 0 3]
[3 2 5 6 4 3 4 3]
[7 0 6 6 4 1 3 5]
[2 0 7 2 4 1 6 3]
[7 2 3 6 4 1 3 3]
[6 6 7 6 4 1 0 5]
[3 6 7 2 0 1 6 6]
[6 0 7 0 6 1 3 3]
[1 5 7 6 4 1 3 6]
[7 2 7 6 7 1 5 3]
[6 0 1 6 7 1 1 3]
[7 1 7 6 4 1 3 3]
[6 1 0 6 4 1 3 3]
[7 0 7 1 4 1 5 3]
[6 0 4 7 4 1 3 3]
[3 5 7 6 4 1 3 3]
[4 6 7 6 4 1 0 3]
[7 1 7 6 4 1 3 3]
[5 1 6 6 4 1 4 3]
[7 1 7 0 4 1 3 3]
[6 6 7 6 0 1 3 3]
[6 0 7 6 6 1 4 4]
[2 0 7 0 4 1 3 3]
[2 4 7 6 4 1 4 3]
[6 0 7 1 4 1 3 3]
[3 0 7 6 4 1 0 3]
[0 0 4 0 4 1 3 5]
[6 0 2 6 4 1 3 3]
[7 1 7 7 4 1 3 3]
[6 6 7 1 2 1 3 2]
[7 0 7 6 4 1 4 3]
[0 1 7 6 2 1 5 2]
[7 6 7 6 4 1 3 3]
[7 6 7 6 4 1 3 3]
[6 2 7 4 4 1 3 3]
[2 3 1 6 4 1 0 5]
[3 6 7 6 4 1 3 3]
[3 0 7 6 4 1 3 6]
[7 5 7 6 4 1 3 3]
[1 5 4 6 4 1 3 3]
[6 1 6 7 0 5 1 3]
[6 5 7 0 4 1 3 3]
[7 0 7 5 5

[6 4 7 6 4 1 6 5]
[6 3 7 0 2 1 5 6]
[6 0 7 6 4 1 5 3]
[5 0 7 7 5 1 1 3]
[7 3 7 0 4 1 6 5]
[7 1 7 4 4 1 3 5]
[2 6 7 6 4 1 1 3]
[7 0 7 0 4 1 3 3]
[5 4 7 0 4 1 5 3]
[3 5 7 6 6 1 3 2]
[7 6 5 6 2 1 3 3]
[2 1 7 2 4 1 3 3]
[5 1 7 3 4 1 3 3]
[2 0 7 0 4 1 3 7]
[6 0 7 6 4 1 1 5]
[3 4 7 4 4 1 3 3]
[5 4 7 1 4 1 4 3]
[6 1 7 0 4 1 5 6]
[3 6 7 6 4 1 3 7]
[2 3 7 6 4 1 3 2]
[6 0 4 2 4 1 3 5]
[4 0 7 1 4 1 3 4]
[7 1 7 6 4 1 6 3]
[7 4 6 6 0 1 5 5]
[1 0 7 0 1 1 3 3]
[7 1 7 6 4 1 3 3]
[7 6 7 6 4 1 3 5]
[7 0 7 2 4 1 3 5]
[7 0 7 6 4 1 4 3]
[2 1 7 6 4 1 3 3]
[5 5 7 6 4 1 3 3]
[5 1 7 6 4 1 3 2]
[3 4 7 6 6 1 6 3]
[0 0 7 0 4 1 5 3]
[6 0 7 6 4 1 3 3]
[3 0 7 1 4 1 4 5]
[7 0 7 6 4 1 3 3]
[3 5 7 2 4 1 6 3]
[5 0 7 6 4 1 3 3]
[2 5 7 0 4 1 0 3]
[7 6 7 0 4 1 3 5]
[7 0 7 6 2 1 1 2]
[6 0 7 6 6 1 5 3]
[2 0 7 6 4 1 5 3]
[6 0 7 6 4 1 3 3]
[7 1 7 7 4 1 3 3]
[7 7 7 0 4 1 3 5]
[7 4 7 4 5 1 3 5]
[2 2 7 0 4 1 3 3]
[2 4 7 6 4 1 3 3]
[3 4 6 6 3 1 3 5]
[1 0 7 0 4 1 3 3]
[6 3 7 1 6 1 5 5]
[2 0 7 6 4 1 5 3]
[3 6 7 4 4 1 3 3]
[3 0 7 0 4

[7 3 3 6 6 1 3 3]
[5 4 7 6 4 1 3 3]
[6 4 6 0 2 1 3 3]
[2 0 7 6 4 1 3 3]
[6 0 7 6 4 1 5 3]
[2 0 7 6 4 1 4 3]
[6 0 7 6 4 1 3 2]
[1 3 7 1 4 1 3 4]
[7 5 6 2 4 1 3 3]
[6 0 7 3 4 1 3 3]
[7 0 7 0 4 1 3 3]
[1 6 7 1 4 1 3 3]
[3 4 7 6 4 1 3 5]
[5 3 7 6 4 1 3 3]
[4 0 3 6 4 1 5 3]
[2 4 7 6 4 1 3 3]
[3 6 7 6 4 1 3 3]
[5 2 7 6 4 1 3 3]
[5 0 7 6 6 1 5 3]
[7 0 7 6 2 1 3 3]
[1 0 7 6 4 1 5 3]
[4 0 7 0 4 1 3 3]
[2 0 7 6 4 1 3 5]
[4 0 1 1 4 1 3 5]
[6 0 7 6 4 1 1 7]
[6 0 7 6 4 1 3 5]
[2 3 7 0 4 1 3 3]
[6 0 7 6 4 1 3 3]
[2 0 7 6 7 1 3 3]
[2 3 7 6 4 1 3 3]
[6 5 7 0 4 1 3 4]
[6 4 7 6 4 1 3 5]
[7 2 7 6 4 1 3 2]
[2 0 7 7 2 1 3 3]
[2 0 7 0 4 1 3 3]
[2 1 7 0 4 1 3 3]
[2 0 7 6 4 1 3 3]
[6 4 7 6 4 1 3 3]
[2 0 7 0 4 1 3 3]
[6 0 7 3 4 1 3 3]
[6 0 7 6 4 1 3 1]
[1 1 7 6 6 1 5 3]
[6 4 7 6 0 1 3 3]
[2 0 7 6 4 1 6 3]
[0 0 7 0 0 1 3 3]
[3 6 7 6 4 1 1 3]
[2 6 7 6 4 1 3 5]
[6 4 7 6 4 1 3 3]
[2 4 7 6 6 1 3 7]
[2 0 7 0 4 1 3 3]
[3 7 7 6 4 1 3 3]
[5 4 7 6 4 1 5 2]
[7 6 1 6 6 1 3 5]
[1 0 7 7 4 1 3 7]
[7 6 7 6 3 1 6 7]
[7 6 7 1 4

[7 3 7 0 4 1 3 3]
[7 5 6 6 4 1 3 3]
[2 0 7 6 6 1 3 4]
[1 0 7 6 4 1 3 3]
[7 0 7 4 4 1 3 2]
[3 0 7 6 4 1 3 3]
[7 1 7 6 6 1 3 5]
[2 0 7 2 4 1 3 3]
[7 5 3 6 2 1 4 5]
[7 6 7 6 4 1 5 2]
[7 4 7 6 4 1 3 3]
[2 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 6 7 6 4 1 4 3]
[2 0 7 6 4 1 3 3]
[2 4 7 6 4 1 1 5]
[6 0 7 0 4 1 3 3]
[6 0 2 0 4 1 3 5]
[5 5 7 6 4 1 3 3]
[7 5 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 4 7 6 4 1 3 3]
[6 6 7 0 4 1 3 3]
[7 4 7 6 4 1 3 5]
[1 6 7 6 4 1 3 4]
[7 6 7 6 4 1 3 5]
[6 4 7 6 4 1 3 5]
[7 0 7 5 4 1 3 3]
[7 5 7 6 2 1 5 3]
[7 0 3 6 4 1 3 3]
[7 4 7 6 4 1 3 3]
[6 0 7 6 4 1 5 5]
[6 6 7 6 4 1 3 3]
[7 1 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[2 6 5 0 4 1 3 5]
[2 6 7 6 4 1 3 3]
[2 6 3 6 4 1 6 3]
[6 0 7 6 4 1 3 3]
[3 0 7 2 4 1 3 3]
[7 0 7 0 4 1 1 3]
[0 0 7 6 4 1 3 5]
[6 1 7 5 4 1 3 3]
[6 4 7 2 4 1 5 5]
[1 6 3 3 4 1 4 3]
[7 4 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[1 4 7 6 4 1 3 3]
[7 0 7 3 4 1 3 3]
[2 6 7 6 4 1 3 3]
[1 5 7 0 4 1 3 5]
[7 6 2 6 4 1 6 3]
[6 2 7 4 4 1 3 3]
[6 0 2 0 6

[6 0 7 0 4 1 3 3]
[7 0 7 3 4 1 3 3]
[7 3 7 6 4 1 3 3]
[7 4 7 6 4 1 3 3]
[2 1 0 6 4 1 3 5]
[7 6 7 6 4 1 3 3]
[6 3 7 0 4 1 3 3]
[6 0 1 6 4 1 3 3]
[7 0 7 6 4 1 5 3]
[5 0 7 7 4 1 3 3]
[6 2 7 6 1 1 3 3]
[2 3 7 6 4 1 5 3]
[6 0 6 6 4 1 3 5]
[6 0 7 6 4 1 5 3]
[6 7 7 0 4 1 4 3]
[7 0 7 6 4 1 3 3]
[5 0 7 3 4 1 3 5]
[6 0 7 6 4 1 3 3]
[1 7 6 6 4 1 3 3]
[6 3 7 0 4 1 3 3]
[7 6 6 6 3 1 3 3]
[7 0 6 0 1 1 3 3]
[7 3 7 0 4 1 3 3]
[6 3 7 7 4 1 5 3]
[7 6 7 6 4 1 5 3]
[7 3 7 6 1 1 3 5]
[6 4 7 6 4 1 3 2]
[6 3 7 6 4 1 3 3]
[6 0 7 0 4 1 3 3]
[7 0 7 6 4 1 3 3]
[2 4 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 4 7 1 4 1 5 3]
[6 3 7 6 4 1 3 5]
[6 0 7 0 4 1 3 4]
[7 7 7 2 4 1 3 3]
[7 0 7 6 4 1 5 5]
[4 0 7 6 6 1 3 3]
[2 1 7 6 4 1 3 3]
[7 3 7 6 0 1 5 3]
[7 4 7 6 4 1 3 3]
[6 0 7 0 4 1 3 3]
[6 4 7 6 4 1 3 4]
[4 0 7 3 4 1 3 5]
[7 0 7 6 4 1 6 3]
[0 3 7 0 4 1 3 3]
[7 6 7 0 4 1 3 3]
[7 0 7 6 4 1 5 3]
[7 0 7 5 4 1 3 3]
[4 6 7 6 4 1 6 3]
[7 4 7 6 4 1 5 3]
[6 6 7 6 4 1 3 3]
[6 0 5 6 4 1 3 5]
[7 7 7 0 4 1 5 3]
[7 5 7 6 4 1 3 3]
[1 7 4 6 4

[6 3 6 0 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 4 6 6 4 1 5 3]
[7 0 7 6 4 1 5 4]
[7 3 7 0 4 1 3 3]
[5 0 6 2 4 1 3 2]
[6 3 7 6 4 1 3 3]
[5 0 7 6 4 1 5 3]
[2 4 7 6 4 1 3 5]
[6 0 7 6 4 1 3 3]
[6 4 7 5 4 1 3 5]
[2 0 7 0 4 1 3 3]
[3 2 7 6 1 1 5 4]
[6 3 7 0 4 1 0 3]
[7 2 7 0 4 1 3 3]
[7 1 7 0 4 1 3 3]
[7 1 7 0 4 1 3 3]
[7 4 7 0 4 1 3 3]
[6 2 7 3 4 1 3 5]
[6 4 6 6 4 1 3 3]
[7 0 7 2 4 1 5 3]
[3 4 7 0 4 1 3 3]
[6 0 3 6 4 1 3 3]
[7 2 7 0 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 6 7 6 4 1 3 3]
[6 2 7 4 4 1 5 5]
[5 3 7 6 4 1 3 3]
[6 1 7 7 4 1 3 3]
[2 4 7 6 4 1 3 3]
[7 1 3 6 4 1 5 3]
[7 4 3 3 4 1 3 3]
[6 0 7 6 4 1 5 3]
[7 0 7 0 4 1 3 5]
[2 0 7 7 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 0 4 1 3 3]
[6 3 7 4 4 1 3 5]
[7 1 7 6 4 1 3 3]
[2 0 7 4 4 1 3 5]
[6 1 7 0 4 1 5 3]
[7 5 7 3 2 1 5 3]
[7 0 7 0 6 1 3 3]
[5 6 7 4 4 1 5 5]
[7 1 1 6 4 1 5 3]
[4 4 6 3 4 1 3 3]
[7 4 7 6 4 1 3 3]
[7 0 7 0 4 1 3 3]
[7 5 7 0 4 1 3 3]
[0 0 7 3 4 1 3 3]
[6 3 7 6 4 1 1 2]
[6 1 7 6 4 1 5 3]
[0 0 7 2 4 1 3 5]
[6 3 7 6 4 1 3 3]
[7 0 7 2 4 1 3 3]
[7 2 7 3 4

[7 0 7 6 4 1 3 3]
[6 4 7 6 4 1 3 5]
[7 3 7 1 4 1 3 3]
[7 6 7 6 4 1 3 3]
[2 5 7 0 4 1 5 3]
[2 4 7 6 4 1 3 3]
[6 6 7 6 4 1 3 5]
[6 4 7 2 4 1 3 3]
[2 2 7 3 4 1 3 3]
[7 2 7 6 4 1 3 5]
[7 4 7 3 4 1 3 3]
[6 5 7 3 4 1 3 3]
[2 6 7 0 1 1 3 3]
[6 4 7 6 0 1 5 3]
[6 4 7 6 4 1 3 3]
[7 2 7 6 4 1 3 3]
[7 0 7 3 4 1 3 3]
[6 0 7 6 4 1 5 5]
[7 0 7 6 4 1 7 3]
[6 4 7 6 4 1 3 3]
[7 0 7 6 4 1 5 3]
[7 0 6 7 0 1 3 3]
[5 0 7 6 4 1 3 3]
[7 1 7 6 4 1 3 3]
[7 1 7 6 4 1 3 3]
[6 0 7 0 4 1 5 3]
[6 0 7 6 4 1 3 3]
[6 4 7 6 4 1 3 3]
[7 3 7 2 3 1 3 7]
[4 0 4 6 4 1 3 3]
[6 3 7 0 4 1 5 2]
[6 0 7 6 4 1 3 2]
[7 4 7 6 4 1 5 3]
[7 4 7 6 4 1 1 7]
[7 5 7 6 4 1 3 6]
[5 4 4 6 4 1 3 3]
[2 5 7 6 0 1 3 3]
[7 3 7 0 4 1 3 5]
[6 0 7 5 4 1 3 3]
[7 0 3 0 4 1 3 3]
[6 4 7 6 4 1 5 3]
[6 6 7 6 4 1 5 5]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 5 3]
[4 4 7 6 4 1 3 3]
[2 0 7 0 4 1 5 5]
[1 3 7 7 4 1 3 3]
[7 7 7 6 4 1 3 3]
[6 4 7 0 4 1 3 3]
[6 0 7 6 4 1 3 5]
[2 3 7 0 2 1 3 3]
[6 4 7 6 4 1 3 3]
[4 4 7 6 4 1 4 2]
[7 5 7 6 4 1 3 2]
[6 4 7 6 4 1 3 3]
[6 0 7 6 4

[7 0 7 6 4 1 5 3]
[7 6 7 6 4 1 3 2]
[6 3 5 6 4 1 3 3]
[7 3 7 7 4 1 3 3]
[5 3 7 6 1 1 3 3]
[6 2 7 6 0 1 5 3]
[7 3 6 6 0 1 3 5]
[5 3 6 6 4 1 3 5]
[6 0 4 2 0 1 3 5]
[7 0 7 6 4 1 3 3]
[6 3 7 6 4 1 3 3]
[7 1 7 2 4 1 3 4]
[7 3 7 6 0 1 3 3]
[7 0 7 6 4 1 3 3]
[6 3 7 6 4 1 3 3]
[7 0 7 6 4 1 3 5]
[6 0 7 6 4 1 3 3]
[7 4 2 6 4 1 5 3]
[2 3 7 6 4 1 3 3]
[5 6 7 6 4 5 3 3]
[7 0 7 0 4 1 3 5]
[6 4 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[2 0 6 0 4 1 3 4]
[6 0 7 6 4 1 3 7]
[6 0 7 6 0 1 3 5]
[1 3 7 6 4 1 3 2]
[7 0 7 6 4 1 3 3]
[2 4 7 6 4 1 3 3]
[6 0 7 7 0 1 3 3]
[7 6 7 0 0 1 3 5]
[7 3 7 6 4 1 3 3]
[1 0 6 7 2 1 3 5]
[6 0 7 6 4 1 5 3]
[7 3 7 6 4 1 0 3]
[6 0 7 0 4 1 3 5]
[6 0 7 6 1 1 5 3]
[6 4 6 2 4 1 3 3]
[7 0 7 6 4 1 3 5]
[7 6 7 0 4 1 3 3]
[5 0 7 6 5 1 1 3]
[7 0 7 6 4 1 5 3]
[7 0 7 6 4 1 3 3]
[7 6 7 0 4 1 3 3]
[6 0 7 6 5 1 3 3]
[7 0 7 3 4 1 3 3]
[7 4 7 6 4 1 3 3]
[7 4 7 6 4 1 3 4]
[7 0 7 6 4 1 3 3]
[2 0 7 6 4 1 3 3]
[7 0 7 6 2 1 4 3]
[7 4 7 6 4 1 3 4]
[7 3 7 0 4 1 3 3]
[7 4 6 1 4 1 5 3]
[2 0 7 3 4 1 3 3]
[6 3 7 7 4

[6 4 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 4 4 1 3 3]
[7 0 7 0 4 1 3 3]
[6 2 6 6 4 1 3 3]
[6 4 5 2 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 3 7 6 4 1 5 3]
[7 0 7 6 4 1 5 3]
[7 0 7 6 4 1 3 3]
[7 0 7 0 4 1 3 3]
[7 4 7 0 4 1 3 3]
[6 0 7 3 4 1 5 3]
[3 4 7 2 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 7 7 6 4 1 3 3]
[7 0 7 6 4 1 3 2]
[6 4 7 6 0 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 1 1 3 3]
[7 0 7 0 4 1 3 3]
[6 6 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[2 0 7 3 0 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 6 1 3 3]
[6 2 7 6 5 1 5 3]
[6 0 7 6 0 1 3 3]
[7 2 7 6 6 1 3 3]
[7 0 7 6 0 1 3 3]
[7 5 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 4 7 6 4 1 3 3]
[6 2 7 6 6 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 5 3]
[7 0 7 6 4 1 3 3]
[6 4 7 6 4 1 3 3]
[6 6 7 6 0 1 3 3]
[4 0 7 6 4 1 3 3]
[7 0 7 6 5 1 3 3]
[7 0 7 6 6 1 3 3]
[6 1 7 6 1 1 3 3]
[7 4 7 0 6 1 3 3]
[6 0 7 6 4 1 3 3]
[6 3 7 2 4 1 3 3]
[7 0 0 6 4 1 3 3]
[1 0 7 6 4 1 3 3]
[7 4 7 6 4 1 3 4]
[6 6 7 6 4 1 3 3]
[7 2 7 6 4 1 3 3]
[3 4 7 6 4

[3 2 7 6 4 1 3 3]
[6 2 7 3 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 6 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 6 7 6 4 1 3 3]
[6 0 7 3 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 6 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 6 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 4 7 6 4 1 0 3]
[1 0 7 6 4 1 6 2]
[6 4 7 6 4 1 3 3]
[3 0 7 6 4 1 3 3]
[6 6 7 6 4 1 3 3]
[6 0 7 4 4 1 3 3]
[7 0 7 3 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 5]
[7 0 7 6 3 1 3 3]
[6 0 7 6 4 1 3 3]
[2 0 7 6 4 1 3 3]
[6 3 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 6 7 6 4 1 3 3]
[3 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[6 4 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 5]
[6 6 7 6 4 1 3 3]
[7 0 7 6 6 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 3 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 6 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[4 4 7 6 4 1 3 3]
[7 0 7 6 4

[7 0 7 6 4 1 3 3]
[5 6 7 6 4 1 3 3]
[6 6 7 3 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 5 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 0 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 2 4 1 3 3]
[5 0 7 2 4 1 3 3]
[7 0 7 6 0 1 3 3]
[7 0 7 6 4 1 3 5]
[7 6 7 3 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 2 4 1 3 3]
[7 0 4 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 1 1 3 3]
[7 0 7 0 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 5 7 6 4 1 3 3]
[6 5 7 0 4 1 3 3]
[7 2 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 6 7 6 4 1 3 3]
[7 0 7 6 4 1 3 2]
[7 0 7 6 4 1 3 3]
[7 5 7 6 4 1 3 3]
[7 6 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 5]
[7 0 7 2 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 6 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[3 0 7 6 4 1 3 3]
[7 0 6 6 4 1 3 5]
[7 0 7 0 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 2 4 1 3 3]
[7 0 7 0 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 1 4 1 3 3]
[6 0 6 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 5 3]
[7 3 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 6 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 1

[7 5 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[1 1 7 6 4 1 3 3]
[7 0 7 6 4 1 5 3]
[7 0 7 3 4 1 3 3]
[7 4 7 6 4 1 3 3]
---------------------------------
| explained_variance | 0.000243 |
| fps                | 263      |
| nupdates           | 4000     |
| policy_entropy     | 3.62     |
| total_timesteps    | 20000    |
| value_loss         | 27.9     |
---------------------------------
[7 0 7 6 4 1 3 3]
[7 0 6 6 4 1 3 3]
[7 7 7 6 4 1 3 3]
[6 0 7 1 4 1 3 3]
[6 0 7 6 4 1 3 5]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 3 7 6 2 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 4 4 1 3 3]
[7 3 7 6 4 1 3 3]
[6 6 7 6 4 1 3 5]
[7 0 7 6 4 1 3 3]
[6 0 7 3 4 1 3 3]
[7 4 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 5]
[7 4 7 6 4 1 3 3]
[6 4 7 6 4 1 3 3]
[6 0 7 0 4 1 3 3]
[7 6 7 6 4 1 3 3]
[6 0 7 3 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 3 0 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 5]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 0 4 1 3 3]
[7 0 7 6

[5 6 7 6 4 1 3 3]
[5 6 7 2 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 6 7 4 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 3 4 1 3 3]
[7 6 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 0 0 1 3 3]
[6 6 7 3 4 1 3 3]
[7 4 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 5 7 6 4 1 3 3]
---------------------------------
| explained_variance | 0.000239 |
| fps                | 265      |
| nupdates           | 4100     |
| policy_entropy     | 3.4      |
| total_timesteps    | 20500    |
| value_loss         | 26.5     |
---------------------------------
[6 0 7 0 4 1 3 3]
[6 4 7 6 0 1 3 3]
[5 0 7 6 6 1 3 3]
[7 6 7 6 4 1 3 3]
[7 4 7 6 4 1 3 3]
[6 0 7 4 0 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[6 7 7 6 3 1 3 3]
[7 4 7 6 4 1 3 3]
[5 1 7 6 4 1 3 4]
[7 0 7 6 4 1 3 5]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 3 4 1 3 3]
[6 6 7 6 4 1 3 3]
[7 4 7 6 4 1 3 3]
[6 6 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 4 7 6

[6 0 7 6 4 1 3 3]
[7 6 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 3 4 1 3 3]
[7 3 7 6 4 1 3 3]
[5 0 7 3 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 5]
[6 5 7 1 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 5]
[7 0 7 6 4 1 3 3]
[7 0 7 6 2 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 5 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 3 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 7 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 4 7 6 4 1 3 5]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 6 7 2 4 1 3 4]
[6 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 0 4 1 3 3]
[0 0 7 6 4

[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 6 7 6 4 1 3 3]
[6 0 7 6 4 1 3 4]
[5 0 7 2 4 1 3 5]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 4 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 6 7 6 4 1 3 3]
[7 7 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 6 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 7 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 2]
[6 0 7 6 4 1 3 3]
[6 4 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 2]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 4 7 0 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 1 1 3 3]
[7 0 7 6 4 1 3 3]
[7 4 7 2 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 4 7 6 4

[7 0 7 6 4 1 3 5]
[7 4 7 6 4 1 5 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 5]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 5]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 4]
[7 0 7 6 4 1 5 3]
[6 4 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 2]
[7 0 7 6 4 1 3 3]
[7 6 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 5]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 6 7 6 4 1 3 3]
[7 4 7 6 4 1 3 3]
[1 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 0 4 1 3 3]
[7 0 7 6 4 1 3 3]
[1 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 3 4 1 5 3]
[7 0 7 0 4

[6 0 7 6 0 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 4]
[5 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[1 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 3 4 1 3 3]
[6 0 7 6 4 1 3 3]
[0 0 7 6 4 1 3 3]
[3 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4

[7 0 7 6 4 1 3 0]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 4]
[7 0 7 6 4 1 3 3]
[0 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[1 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[6 0 7 6 3 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 0 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4

[7 0 7 6 4 1 5 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 5 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 3 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[1 0 7 6 4 1 3 3]
[7 0 7 2 4 1 3 3]
[7 0 7 3 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 1 1 3 3]
[6 0 7 6 4 1 3 3]
[1 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 5 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[1 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4

[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 6 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4

[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[1 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 5 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 3 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4

[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 0 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[6 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[5 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4 1 3 3]
[7 0 7 6 4

---------------------------------
| explained_variance | 0.000232 |
| fps                | 268      |
| nupdates           | 5000     |
| policy_entropy     | 0.4      |
| total_timesteps    | 25000    |
| value_loss         | 15.3     |
---------------------------------
TESTTEST
[7 0 7 6 4 1 3 3]
Observation = 
[0 0 0 0 0 0 0 0]
Reward = 7
[7 0 7 6 4 1 3 3]
Observation = 
[0 0 0 0 0 1 0 0]
Reward = 0
[7 0 7 6 4 1 3 3]
Observation = 
[0 0 0 0 0 0 0 0]
Reward = 7
[7 0 7 6 4 1 3 3]
Observation = 
[0 0 0 0 0 1 0 0]
Reward = 0
[7 0 7 6 4 1 3 3]
Observation = 
[0 0 0 0 0 0 0 0]
Reward = 7
[7 0 7 6 4 1 3 3]
Observation = 
[0 0 0 0 0 1 0 0]
Reward = 0
[7 0 7 6 4 1 3 3]
Observation = 
[0 0 0 0 0 0 0 0]
Reward = 7
[7 0 7 6 4 1 3 3]
Observation = 
[0 0 0 0 0 1 0 0]
Reward = 0
[7 0 7 6 4 1 3 3]
Observation = 
[0 0 0 0 0 0 0 0]
Reward = 7
[7 0 7 6 4 1 3 3]
Observation = 
[0 0 0 0 0 1 0 0]
Reward = 0
[7 0 7 6 4 1 3 3]
Observation = 
[0 0 0 0 0 0 0 0]
Reward = 7
[7 0 7 6 4 1 3 3]
Observation = 
[0 0